import { test } from "node:test";
import assert from "node:assert/strict";
import { existsSync, lstatSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawn } from "node:child_process";
import { eirDigest } from "../src/eir/canonical.js";
import { AuthoritativeAppendV1, AuthoritativeAppendV1HistoryPath, type AuthoritativeAppendV1Checkpoint, type AuthoritativeAppendV1Io } from "../src/spine/authoritative_append_v1.js";
import { EventAdmissionV1HeadDigestDomain, type EventAdmissionV1LineageRecord, type EventAdmissionV1TrustedContext } from "../src/spine/event_admission_v1.js";
import { EventEnvelopeV1CodecIdentity, EventEnvelopeV1Encode, EventEnvelopeV1Schema, type EventEnvelopeV1Value } from "../src/spine/event_envelope_v1.js";

const fresh = () => mkdtempSync(join(tmpdir(), "keep-t003-"));
const profile = { kind: "verified-local-posix-v1" as const, max_record_bytes: 1_048_576n };
const eventId = (v: EventEnvelopeV1Value) => { const r=EventEnvelopeV1Encode(v); if(!r.ok) assert.fail(r.code); return r.event_digest; };
const headId = (history_id:string,sequence:bigint,event_id:string,predecessor_head_id:string|null) => eirDigest(EventAdmissionV1HeadDigestDomain,{history_id,sequence,event_id,predecessor_head_id});
const n1 = (committed_lineage:readonly EventAdmissionV1LineageRecord[]=[]): EventAdmissionV1TrustedContext => ({kind:"n1",track:"n1",history_id:"h-local",actor_id:"owner",authority_domain:"local",custody_id:"disk",committed_lineage,witnessed_head:committed_lineage.length?{sequence:committed_lineage.at(-1)!.sequence,event_id:committed_lineage.at(-1)!.event_id,head_id:committed_lineage.at(-1)!.head_id}:null});
const enterprise = (): EventAdmissionV1TrustedContext => ({kind:"enterprise",track:"enterprise",history_id:"h-enterprise",actor_id:"agent",authority_domain:"org/tenant",custody_id:"hsm",organization_id:"org",tenant_id:"tenant",actor_role_id:"release",isolation_id:"iso",committed_lineage:[],witnessed_head:null});
const proposal = (c:EventAdmissionV1TrustedContext, payload="one"):EventEnvelopeV1Value => { const t=c.committed_lineage.at(-1); return {schema:EventEnvelopeV1Schema,schema_version:1n,codec:EventEnvelopeV1CodecIdentity,codec_version:1n,history_id:c.history_id,sequence:t?t.sequence+1n:0n,predecessor_event_id:t?.event_id??null,predecessor_head_id:t?.head_id??null,event_type:"goal.admitted",actor_id:c.actor_id,authority_domain:c.authority_domain,track:c.track,payload:{value:payload},effect_correlation:null}; };
const append = (root:string,p:unknown,c:EventAdmissionV1TrustedContext,io?:Partial<AuthoritativeAppendV1Io>) => new AuthoritativeAppendV1({storage_root:root,durability_profile:profile,...(io===undefined?{}:{io})}).append(p,c);

const childRoot=process.env.KEEP_T003_CHILD_ROOT;
if(childRoot!==undefined){const c=n1(),stop=process.env.KEEP_T003_CHILD_STOP as AuthoritativeAppendV1Checkpoint|undefined;const r=await append(childRoot,proposal(c,process.env.KEEP_T003_CHILD_PAYLOAD??"child"),c,stop===undefined?undefined:{checkpoint:p=>{if(p===stop)process.kill(process.pid,"SIGKILL");}});process.exit(r.ok?0:2);}
const runChild=(root:string,payload:string,stop?:AuthoritativeAppendV1Checkpoint)=>new Promise<{code:number|null;signal:NodeJS.Signals|null}>((resolve,reject)=>{const child=spawn(process.execPath,[new URL(import.meta.url).pathname],{env:{...process.env,KEEP_T003_CHILD_ROOT:root,KEEP_T003_CHILD_PAYLOAD:payload,...(stop===undefined?{}:{KEEP_T003_CHILD_STOP:stop})},stdio:"ignore"});child.once("error",reject);child.once("exit",(code,signal)=>resolve({code,signal}));});

test("PG-05-T003-FC01 n1 genesis is durable, replayable, idempotent, and non-authoritative",async()=>{const root=fresh(),c=n1(),p=proposal(c),r=await append(root,p,c);assert.equal(r.ok,true);if(!r.ok)return;assert.deepEqual({durable:r.receipt.durable,witnessed:r.receipt.witnessed,committed:r.receipt.committed,authoritative:r.receipt.authoritative},{durable:true,witnessed:false,committed:false,authoritative:false});assert.deepEqual(new Uint8Array(readFileSync(r.receipt.final_path)),r.receipt.record_bytes);assert.equal(lstatSync(AuthoritativeAppendV1HistoryPath(root,c.history_id)).mode&0o077,0);assert.deepEqual(await append(root,p,c),r);});
test("PG-05-T003-FC02 enterprise attribution is retained and cannot substitute n1",async()=>{const c=enterprise(),p=proposal(c),r=await append(fresh(),p,c);assert.equal(r.ok,true);if(!r.ok)return;assert.equal(r.receipt.authority.kind,"enterprise");if(r.receipt.authority.kind==="enterprise")assert.deepEqual([r.receipt.authority.organization_id,r.receipt.authority.tenant_id,r.receipt.authority.actor_role_id,r.receipt.authority.isolation_id],["org","tenant","release","iso"]);assert.deepEqual(await append(fresh(),{...p,track:"n1"},c),{ok:false,code:"TRACK_AUTHORITY_SUBSTITUTION"});});
test("PG-05-T003-FC03 competing child-process writers yield one winner",async()=>{const root=fresh(),c=n1();const rs=await Promise.all([runChild(root,"a"),runChild(root,"b")]);assert.equal(rs.filter(r=>r.code===0).length,1);assert.equal(rs.filter(r=>r.code===2).length,1);assert.equal(readdirSync(AuthoritativeAppendV1HistoryPath(root,c.history_id)).filter(x=>x.endsWith(".record")).length,1);});
test("PG-05-T003-FC04 irregular short writes are looped to exact completion",async()=>{let calls=0;const root=fresh(),c=n1();const r=await append(root,proposal(c),c,{write:(fd,b,o,l,p,n)=>{calls++;return n(fd,b,o,Math.min(l,calls%3+1),p);}});assert.equal(r.ok,true);if(r.ok){assert.ok(calls>1);assert.deepEqual(new Uint8Array(readFileSync(r.receipt.final_path)),r.receipt.record_bytes);}});
test("PG-05-T003-FC05 ENOSPC after a partial temp write publishes no final",async()=>{let calls=0;const root=fresh(),c=n1();const r=await append(root,proposal(c),c,{write:(fd,b,o,l,p,n)=>{if(calls++===0)return n(fd,b,o,1,p);const e=new Error("full") as NodeJS.ErrnoException;e.code="ENOSPC";throw e;}});assert.deepEqual(r,{ok:false,code:"APPEND_IO_FAILED"});assert.equal(readdirSync(AuthoritativeAppendV1HistoryPath(root,c.history_id)).some(x=>x.endsWith(".record")),false);});
test("PG-05-T003-FC06 actual file and post-link directory fsync failures issue no receipt",async()=>{for(const failCall of [3,4]){let calls=0;const root=fresh(),c=n1();const r=await append(root,proposal(c),c,{fsync:(fd,native)=>{calls++;if(calls===failCall){const e=new Error("sync failed") as NodeJS.ErrnoException;e.code=failCall===3?"ENOSPC":"EIO";throw e;}native(fd);}});assert.equal(r.ok,false);const finals=readdirSync(AuthoritativeAppendV1HistoryPath(root,c.history_id)).filter(x=>x.endsWith(".record"));if(failCall===3)assert.equal(finals.length,0);else assert.equal(finals.length,1);}});
test("PG-05-T003-FC07 unsupported substrate refuses before mutation",async()=>{const root=fresh(),c=n1();const r=await new AuthoritativeAppendV1({storage_root:root,durability_profile:{kind:"unverified-or-network"}}).append(proposal(c),c);assert.deepEqual(r,{ok:false,code:"UNSUPPORTED_DURABILITY_PROFILE"});assert.deepEqual(readdirSync(root),[]);});
test("PG-05-T003-FC08 SIGKILL at every crash window recovers only an empty prefix or complete final",async()=>{for(const stop of ["HISTORY_DIRECTORY_CREATED","HISTORY_DIRECTORY_SYNCED","PARENT_DIRECTORY_SYNCED","TEMP_CREATED","TEMP_FILE_SYNCED","FINAL_LINKED","FINAL_DIRECTORY_SYNCED","TEMP_UNLINKED","CLEANUP_DIRECTORY_SYNCED"] satisfies AuthoritativeAppendV1Checkpoint[]){const root=fresh(),c=n1();const r=await runChild(root,"crash",stop);assert.equal(r.signal,"SIGKILL");const h=AuthoritativeAppendV1HistoryPath(root,c.history_id);if(existsSync(h)){const finals=readdirSync(h).filter(x=>x.endsWith(".record"));assert.ok(finals.length<=1);if(finals[0])assert.ok(readFileSync(join(h,finals[0])).length>3);}const recovered=await runChild(root,"crash");assert.equal(recovered.code,0);assert.equal(readdirSync(h).filter(x=>x.endsWith(".record")).length,1);}});
test("PG-05-T003-FC09 malformed deterministic final fences without repair",async()=>{const root=fresh(),c=n1(),h=AuthoritativeAppendV1HistoryPath(root,c.history_id),path=join(h,`0000000000000000-${"a".repeat(64)}.record`);mkdirSync(h,{mode:0o700});writeFileSync(path,new Uint8Array([1,2,3]),{mode:0o600});assert.deepEqual(await append(root,proposal(c),c),{ok:false,code:"APPEND_DURABILITY_UNPROVEN"});assert.deepEqual(new Uint8Array(readFileSync(path)),new Uint8Array([1,2,3]));});
