import { test } from "node:test";
import assert from "node:assert/strict";
import { generateKeyPairSync, sign } from "node:crypto";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { encodeCanonical, eirDigest } from "../src/eir/canonical.js";
import { AuthoritativeAppendV1 } from "../src/spine/authoritative_append_v1.js";
import { replayAuthoritativeHistoryV1, type AuthoritativeReplayV1Event, type AuthoritativeReplayV1Request } from "../src/spine/authoritative_replay_v1.js";
import { CommittedHeadV1, type CommittedHeadV1Result, type CommittedHeadV1WitnessAck, type CommittedHeadV1WitnessPort } from "../src/spine/committed_head_v1.js";
import { EventAdmissionV1HeadDigestDomain, type EventAdmissionV1LineageRecord, type EventAdmissionV1TrustedContext } from "../src/spine/event_admission_v1.js";
import { EventEnvelopeV1CodecIdentity, EventEnvelopeV1Schema, EventEnvelopeV1Encode, type EventEnvelopeV1Value } from "../src/spine/event_envelope_v1.js";
import { ReducerRegistryV1 } from "../src/spine/reducer_registry_v1.js";
import { EventVersionRegistryV1 } from "../src/spine/version_registry_v1.js";

const keys=generateKeyPairSync("ed25519"),publicKey=keys.publicKey.export({type:"spki",format:"pem"}).toString();
class Witness implements CommittedHeadV1WitnessPort{current:CommittedHeadV1WitnessAck|null=null;async latest(){return this.current}async compareAndPersist(expected:string|null,bytes:Uint8Array){assert.equal(this.current?.ok===true?this.current.checkpoint_digest:null,expected);return this.current={ok:true,durable:true,checkpoint_bytes:bytes.slice(),checkpoint_digest:eirDigest("keep.spine.committed-head-checkpoint-bytes.v1",bytes),signature:new Uint8Array(sign(null,bytes,keys.privateKey))}}}
const base=(kind:"n1"|"enterprise",lineage:readonly EventAdmissionV1LineageRecord[]=[]):EventAdmissionV1TrustedContext=>kind==="n1"?{kind:"n1",track:"n1",history_id:"replay-n1",actor_id:"owner",authority_domain:"local",custody_id:"disk",committed_lineage:lineage,witnessed_head:lineage.length?{sequence:lineage.at(-1)!.sequence,event_id:lineage.at(-1)!.event_id,head_id:lineage.at(-1)!.head_id}:null}:{kind:"enterprise",track:"enterprise",history_id:"replay-enterprise",actor_id:"agent",authority_domain:"org/tenant",custody_id:"hsm",organization_id:"org",tenant_id:"tenant",actor_role_id:"release",isolation_id:"iso",committed_lineage:lineage,witnessed_head:lineage.length?{sequence:lineage.at(-1)!.sequence,event_id:lineage.at(-1)!.event_id,head_id:lineage.at(-1)!.head_id}:null};
const proposal=(c:EventAdmissionV1TrustedContext,value:string,effect:string|null=null):EventEnvelopeV1Value=>{const p=c.committed_lineage.at(-1);return{schema:EventEnvelopeV1Schema,schema_version:1n,codec:EventEnvelopeV1CodecIdentity,codec_version:1n,history_id:c.history_id,sequence:p?p.sequence+1n:0n,predecessor_event_id:p?.event_id??null,predecessor_head_id:p?.head_id??null,event_type:"goal.admitted",actor_id:c.actor_id,authority_domain:c.authority_domain,track:c.track,payload:{value,effect_status:effect},effect_correlation:null}};
async function fixture(kind:"n1"|"enterprise"="n1",eventCount=2){
  const append=new AuthoritativeAppendV1({storage_root:mkdtempSync(join(tmpdir(),"keep-t009-")),durability_profile:{kind:"verified-local-posix-v1",max_record_bytes:1_048_576n}}),witness=new Witness(),committer=new CommittedHeadV1({append,history_storage_domain:"history",witness_storage_domain:"witness",witness,witness_public_key:publicKey}),lineage:EventAdmissionV1LineageRecord[]=[],proposals:EventEnvelopeV1Value[]=[];let final:CommittedHeadV1Result|null=null;
  for(const [value,effect] of ([ ["intent","uncertain"],["result","resolved"] ] as const).slice(0,eventCount)){const c=base(kind,lineage),p=proposal(c,value,effect);final=await committer.commit(p,c);assert.equal(final.ok,true);if(!final.ok)throw new Error("fixture commit");proposals.push(p);lineage.push({sequence:final.receipt.sequence,event_id:final.receipt.event_id,head_id:final.receipt.next_head_id,predecessor_event_id:p.predecessor_event_id,predecessor_head_id:p.predecessor_head_id});}
  if(final===null||!final.ok)throw new Error("fixture head");const versions=new EventVersionRegistryV1([{event_type:"goal.admitted",from_version:1n,to_version:2n,upcaster_id:"goal-v1-v2",upcaster_version:1n,operation:"retain-payload"}]),set=versions.interpreterSet("goal.admitted",1n,2n);assert.equal(set.ok,true);if(!set.ok)throw new Error("set");const events:AuthoritativeReplayV1Event[]=proposals.map(p=>({proposal:p,target_version:2n,interpreter_set_digest:set.interpreter_set_digest}));
  const request:AuthoritativeReplayV1Request={committed_head:final,authority_context:base(kind),events,initial_state_bytes:encodeCanonical({value:"initial"}),versions,reducers:new ReducerRegistryV1([{event_type:"goal.admitted",event_schema_version:1n,reducer_id:"goal",reducer_version:1n,transition:"replace-state-with-event-payload",capabilities:[]}])};return{request,events};
}
test("PG-05-T009-FC01 full and chunked n1 replay return byte-identical state and receipt",async()=>{const f=await fixture(),a=replayAuthoritativeHistoryV1(f.request),b=replayAuthoritativeHistoryV1({...f.request,events:[[f.events[0]!],[f.events[1]!]]});assert.equal(a.ok,true);assert.equal(b.ok,true);if(a.ok&&b.ok){assert.deepEqual(a.state_bytes,b.state_bytes);assert.deepEqual(a.receipt,b.receipt);assert.equal(a.result_digest,b.result_digest)}});
test("PG-05-T009-FC02 enterprise replay directly retains tenant authority",async()=>{const r=replayAuthoritativeHistoryV1((await fixture("enterprise")).request);assert.equal(r.ok,true);if(r.ok){assert.equal(r.receipt.authority.kind,"enterprise");if(r.receipt.authority.kind==="enterprise")assert.deepEqual([r.receipt.authority.organization_id,r.receipt.authority.tenant_id,r.receipt.authority.actor_role_id,r.receipt.authority.isolation_id],["org","tenant","release","iso"])}});
test("PG-05-T009-FC03 committed intent uncertainty is reduced as data",async()=>{const r=replayAuthoritativeHistoryV1((await fixture("n1",1)).request);assert.equal(r.ok,true);if(r.ok)assert.deepEqual(r.state_bytes,encodeCanonical({value:"intent",effect_status:"uncertain"}))});
test("PG-05-T009-FC04 replay exposes no actuator and performs zero effects",async()=>{let calls=0;const actuator=()=>calls++;const r=replayAuthoritativeHistoryV1((await fixture()).request);void actuator;assert.equal(r.ok,true);assert.equal(calls,0);if(r.ok)assert.equal(r.receipt.effects_performed,false)});
test("PG-05-T009-FC05 incomplete committed provenance is refused",async()=>{const f=await fixture(),receipt={...f.request.committed_head.receipt} as Record<string,unknown>;delete receipt.checkpoint_digest;assert.deepEqual(replayAuthoritativeHistoryV1({...f.request,committed_head:{ok:true,receipt} as unknown as Extract<CommittedHeadV1Result,{ok:true}>}),{ok:false,code:"TRACK_AUTHORITY_SUBSTITUTION"})});
test("PG-05-T009-FC06 forged projection cannot change history-derived state",async()=>{const f=await fixture(),r=replayAuthoritativeHistoryV1({...f.request,projection:{schema:"keep.spine.replay-projection",schema_version:1n}});assert.equal(r.ok,true);if(r.ok)assert.deepEqual(r.state_bytes,encodeCanonical({value:"result",effect_status:"resolved"}))});
test("PG-05-T009-FC07 combined malformed, linkage, authority, version and reducer faults return physical first",async()=>{const f=await fixture(),bad={proposal:null,target_version:9n,interpreter_set_digest:"x"};assert.deepEqual(replayAuthoritativeHistoryV1({...f.request,events:[bad as unknown as AuthoritativeReplayV1Event,f.events[0]!]}),{ok:false,code:"PHYSICAL_HISTORY_INVALID"})});
test("PG-05-T009-FC08 logical reorder fails linkage and validated-shape drift fails determinism",async()=>{const f=await fixture();assert.deepEqual(replayAuthoritativeHistoryV1({...f.request,events:[f.events[1]!,f.events[0]!]}),{ok:false,code:"HISTORY_INTEGRITY_MISMATCH"});const baseline=replayAuthoritativeHistoryV1(f.request);assert.equal(baseline.ok,true);if(baseline.ok)assert.deepEqual(replayAuthoritativeHistoryV1({...f.request,expected_result_digest:"f".repeat(64)}),{ok:false,code:"REPLAY_DETERMINISM_MISMATCH"})});
test("PG-05-T009 precedence and interpreter/reducer refusals are direct",async()=>{const f=await fixture(),receipt={...f.request.committed_head.receipt} as Record<string,unknown>;delete receipt.checkpoint_digest;assert.deepEqual(replayAuthoritativeHistoryV1({...f.request,committed_head:{ok:true,receipt} as unknown as Extract<CommittedHeadV1Result,{ok:true}>,events:[{proposal:null,target_version:2n,interpreter_set_digest:"f".repeat(64)}]}),{ok:false,code:"PHYSICAL_HISTORY_INVALID"});const drift=[...f.events];drift[0]={...drift[0]!,interpreter_set_digest:"f".repeat(64)};assert.deepEqual(replayAuthoritativeHistoryV1({...f.request,events:drift}),{ok:false,code:"VERSION_INTERPRETER_REFUSED"});assert.deepEqual(replayAuthoritativeHistoryV1({...f.request,reducers:new ReducerRegistryV1([])}),{ok:false,code:"REDUCTION_REFUSED"})});
