import test from "node:test";
import assert from "node:assert/strict";
import {
  decompositionPublicationDigest,
  verifyDecompositionPublication,
  type DecompositionPublicationInputV1,
  type DecompositionPublicationManifestV1,
} from "../src/decomposition/decomposition_publication.js";
import { decompositionApprovalDigest, type DecompositionGenerationRecordV1 } from "../src/decomposition/decomposition_approval.js";

const h=(c:string)=>c.repeat(64),oid=(c:string)=>c.repeat(40), generation=`sha256:${h("1")}`;
const members=[{path:"planning/decomposition/graph.json",sha256:h("a")},{path:"planning/decomposition/approval.json",sha256:h("b")}];
function manifest(track:"n1"|"enterprise"="n1"):DecompositionPublicationManifestV1{return {schema_version:1,generation,authority_digest:h(track==="n1"?"c":"d"),members};}
function record(m=manifest()):DecompositionGenerationRecordV1 {const body={schema_version:1 as const,generation,parent_record_digest:null,graph_digest:h("2"),candidate_digest:h("3"),manifest_digest:decompositionPublicationDigest(m),scope_digest:h("4"),scope_ids:["n1","enterprise"],amendment_authorization_digest:"GENESIS" as const,evidence_digests:[],review_disposition_digest:h("5"),approval_digest:h("6"),status:"APPROVED" as const};return {...body,record_digest:decompositionApprovalDigest(body)};}
function input(track:"n1"|"enterprise"="n1"):DecompositionPublicationInputV1 {const m=manifest(track),r=record(m);return {schema_version:1,canonical_remote:"https://example.invalid/keep-fixture.git",canonical_ref:"refs/heads/main",expected_remote_commit:oid("7"),expected_product_commit:"a798bf022659983f0fc7c786ce2de358ff9ab80f",approved_generation:r,manifest:m,product_predecessor:{commit:"a798bf022659983f0fc7c786ce2de358ff9ab80f",clean:true},observation:{remote:"https://example.invalid/keep-fixture.git",ref:"refs/heads/main",advertised_commit:oid("7"),fetched_commit:oid("7"),reachable:true,generation,product_commit:"a798bf022659983f0fc7c786ce2de358ff9ab80f",members}};}

test("PG-04-T007-FC01 valid local-owner canonical package readback",()=>{const x=input(),r=verifyDecompositionPublication(x);assert.equal(r.code,"ADVANCED");assert.equal(r.receipt?.remote_commit,x.expected_remote_commit);assert.deepEqual(r.receipt?.members,x.manifest.members);assert.equal(r.receipt?.implementation_authorized,false);});
test("PG-04-T007-FC02 valid enterprise canonical package readback",()=>{const x=input("enterprise"),r=verifyDecompositionPublication(x);assert.equal(r.code,"ADVANCED");assert.equal(r.receipt?.manifest_digest,x.approved_generation.manifest_digest);assert.equal(r.receipt?.remote_commit,x.observation.advertised_commit);assert.deepEqual(r.receipt?.members,x.manifest.members);});
test("PG-04-T007-FC03 local-only commit is not durable",()=>{const x=input();x.observation.reachable=false;assert.equal(verifyDecompositionPublication(x).code,"DECOMPOSITION_NOT_DURABLE");});
test("PG-04-T007-FC04 wrong canonical remote, ref, or head is not durable",()=>{for(const mutate of [(x:DecompositionPublicationInputV1)=>x.observation.remote="other",(x:DecompositionPublicationInputV1)=>x.observation.ref="refs/heads/scratch",(x:DecompositionPublicationInputV1)=>x.observation.advertised_commit=oid("8")]){const x=input();mutate(x);assert.equal(verifyDecompositionPublication(x).code,"DECOMPOSITION_NOT_DURABLE");}});
test("PG-04-T007-FC05 unreachable fetched commit is not durable",()=>{const x=input();x.observation.fetched_commit=oid("8");assert.equal(verifyDecompositionPublication(x).code,"DECOMPOSITION_NOT_DURABLE");});
test("PG-04-T007-FC06 wrong, omitted, and added member bytes are refused",()=>{for(const changed of [[{...members[0]!,sha256:h("f")},members[1]!],[members[0]!],[...members,{path:"extra",sha256:h("e")}]] ){const x=input();x.observation.members=changed;assert.equal(verifyDecompositionPublication(x).code,"DECOMPOSITION_NOT_DURABLE");}});
test("PG-04-T007-FC07 dirty predecessor or unapproved manifest preimage is invalid",()=>{const dirty=input();dirty.product_predecessor.clean=false;assert.equal(verifyDecompositionPublication(dirty).code,"PREREQUISITE_AUTHORITY_INVALID");const unanchored=input();unanchored.manifest.members=[{path:"shortened",sha256:h("f")}];unanchored.observation.members=unanchored.manifest.members;assert.equal(verifyDecompositionPublication(unanchored).code,"PREREQUISITE_AUTHORITY_INVALID");});
test("PG-04-T007-FC08 stale approved generation is refused after durability",()=>{const x=input();x.observation.generation=`sha256:${h("9")}`;assert.equal(verifyDecompositionPublication(x).code,"STALE_DERIVATION");x.observation.reachable=false;assert.equal(verifyDecompositionPublication(x).code,"DECOMPOSITION_NOT_DURABLE");});
test("PG-04-T007-FC09 track-bearing observation payload is malformed",()=>{const x=input() as unknown as Record<string,unknown>;const observation=x.observation as Record<string,unknown>;observation.track="enterprise";assert.equal(verifyDecompositionPublication(x as unknown as DecompositionPublicationInputV1).code,"MALFORMED_OR_UNKNOWN_FIELD");});
test("PG-04-T007-FC10 recovery snapshots once and repeats without implementation authority",()=>{const x=input(),first=verifyDecompositionPublication(x),recovered=structuredClone(x),second=verifyDecompositionPublication(recovered);assert.deepEqual(second,first);assert.equal(second.receipt?.implementation_authorized,false);assert.equal(Object.isFrozen(second.receipt?.members),true);const adversarial=input();let reads=0;Object.defineProperty(adversarial.manifest,"members",{enumerable:true,get:()=>++reads===1?members:[{path:"changed",sha256:h("f")}]});const snapshotted=verifyDecompositionPublication(adversarial);assert.equal(snapshotted.code,"ADVANCED");assert.deepEqual(snapshotted.receipt?.members,members);assert.equal(reads,1);});
