import test from "node:test";
import assert from "node:assert/strict";
import {
  advanceDecompositionApproval,
  decompositionApprovalDigest,
  initialDecompositionApprovalState,
  type DecompositionApprovalActionV1,
  type DecompositionApprovalStateV1,
  type TrustedDecompositionApprovalScopeV1,
  type TrustedDecompositionOwnerContextV1,
} from "../src/decomposition/decomposition_approval.js";
import { decompositionReviewDigest } from "../src/decomposition/decomposition_review.js";

const h=(c:string)=>c.repeat(64), g=(c:string)=>`sha256:${h(c)}`;
const n1={schema_version:1,kind:"n1",owner_id:"owner-1",custody_id:"custody-1",organization_services:"ABSENT"} as const;
const enterprise={schema_version:1,kind:"enterprise",organization_id:"org-1",actor_id:"actor-1",role_id:"approver",separation_policy_id:"four-eyes",custody_evidence_digest:h("a"),isolation_evidence_digest:h("b"),local_owner_substitution:false} as const;

function scope(owner:TrustedDecompositionOwnerContextV1=n1):TrustedDecompositionApprovalScopeV1 {
  const generation=g("1"), graph=h("2"), candidate=h("3"), manifest=h("4"), scopeDigest=h("5");
  const body={schema_version:1 as const,status:"TWO_ROUND_DECOMPOSITION_REVIEW_COMPLETE" as const,generation,candidate_digest:candidate,manifest_digest:manifest,scope_digest:scopeDigest,used:2 as const,reviewers:[{round:1 as const,reviewer_id:"reviewer-a",reviewer_family:"claude",track:"n1" as const},{round:2 as const,reviewer_id:"reviewer-b",reviewer_family:"gemini",track:"enterprise" as const}],repair_chains:[],open_findings:[] as const};
  const transition_state={schema_version:1 as const,phase:"OWNER_APPROVED" as const,approved_graph_digest:graph,active_generation:generation,derived_authorities:{architecture:{digest:h("6"),depends_on:[],status:"ACTIVE" as const},decomposition:{digest:h("7"),depends_on:[h("6")],status:"ACTIVE" as const},owner_approval:{digest:h("8"),depends_on:[h("7")],status:"ACTIVE" as const},ticket_activation:{digest:h("9"),depends_on:[h("8")],status:"ACTIVE" as const}}};
  return {schema_version:1,status:"DECOMPOSITION_APPROVAL_SCOPE_ADMITTED",approved_inventory_digest:"f0b8b60c7b497b6422fc43afeb310d18ea3d28f3decfe666d44deb54963399db",generation,graph_digest:graph,candidate_digest:candidate,manifest_digest:manifest,scope_digest:scopeDigest,parent_scope_ids:["n1","enterprise"],proposed_scope_ids:["n1","enterprise","shared"],candidate_author_id:"builder",candidate_author_family:"codex",expected_owner:owner.kind==="n1"?{kind:"n1",owner_id:owner.owner_id}:{kind:"enterprise",organization_id:owner.organization_id,actor_id:owner.actor_id,role_id:owner.role_id,separation_policy_id:owner.separation_policy_id},transition_state,transition_result:{code:"ADVANCED",advanced:true,state:transition_state,stale_descendants:[],owner_stop:null},observed_graph_digest:null,review_disposition:{...body,disposition_digest:decompositionReviewDigest(body)},architecture_authority_digest:h("6"),decomposition_authority_digest:h("7")};
}
function approval(state:DecompositionApprovalStateV1,s:TrustedDecompositionApprovalScopeV1,owner:TrustedDecompositionOwnerContextV1):DecompositionApprovalActionV1 { const current=state.generations.at(-1)!; const body={schema_version:1,kind:"APPROVE_GENERATION",expected_generation:current.generation,expected_record_digest:current.record_digest,owner,disposition_digest:s.review_disposition!.disposition_digest}; return {schema_version:1,kind:"APPROVE_GENERATION",expected_generation:current.generation,expected_record_digest:current.record_digest,approval_digest:decompositionApprovalDigest(body)}; }
function approved(owner:TrustedDecompositionOwnerContextV1=n1){const s=scope(owner), initial=initialDecompositionApprovalState(s), result=advanceDecompositionApproval(initial,approval(initial,s,owner),owner,s); assert.equal(result.code,"ADVANCED"); return {s,state:result.state!};}

test("PG-04-T006-FC01 exact local owner approves without organization services",()=>{const {state}=approved(); assert.equal(state.generations.at(-1)?.status,"APPROVED"); assert.equal(state.implementation_authorized,false);});
test("PG-04-T006-FC02 attributed enterprise authority approves",()=>{const {state}=approved(enterprise); assert.equal(state.generations.at(-1)?.status,"APPROVED");});
test("PG-04-T006-FC03 approval before two vets is refused",()=>{const s={...scope(),review_disposition:null},state=initialDecompositionApprovalState(s); assert.equal(advanceDecompositionApproval(state,approval(state,scope(),n1),n1,s).code,"OWNER_APPROVAL_INVALID");});
test("PG-04-T006-FC04 candidate author cannot approve",()=>{const s={...scope(),candidate_author_id:n1.owner_id},state=initialDecompositionApprovalState(s); assert.equal(advanceDecompositionApproval(state,approval(state,s,n1),n1,s).code,"OWNER_APPROVAL_INVALID");});
test("PG-04-T006-FC05 stale disposition and wrong authority are refused",()=>{const s=scope(),state=initialDecompositionApprovalState(s),bad={...s,review_disposition:{...s.review_disposition!,candidate_digest:h("f")}}; assert.equal(advanceDecompositionApproval(state,approval(state,s,n1),n1,bad).code,"OWNER_APPROVAL_INVALID"); assert.equal(advanceDecompositionApproval(state,approval(state,s,n1),{...n1,owner_id:"other"},s).code,"OWNER_APPROVAL_INVALID");});
test("PG-04-T006-FC06 mutation appends observation and preserves approval",()=>{const {s,state}=approved(),before=structuredClone(state.generations),mut={...s,observed_graph_digest:h("f"),transition_result:{code:"APPROVED_GRAPH_MUTATED" as const,advanced:false,state:{...s.transition_state,derived_authorities:{...s.transition_state.derived_authorities,owner_approval:{...s.transition_state.derived_authorities.owner_approval,status:"STALE_DERIVATION" as const}}},stale_descendants:["owner_approval" as const],owner_stop:"APPROVED_GRAPH_AMENDMENT_REQUIRES_OWNER" as const}},current=state.generations.at(-1)!; const r=advanceDecompositionApproval(state,{schema_version:1,kind:"OBSERVE_GRAPH",expected_generation:current.generation,expected_record_digest:current.record_digest},n1,mut); assert.equal(r.code,"APPROVED_GRAPH_MUTATED"); assert.equal(r.decision,"OWNER_DECISION"); assert.deepEqual(r.state?.generations,before); assert.equal(r.state?.invalidation_observations[0]?.observed_graph_digest,h("f"));});
function invalidated(){const {s,state}=approved(); const mut={...s,observed_graph_digest:h("f"),transition_result:{code:"APPROVED_GRAPH_MUTATED" as const,advanced:false,state:s.transition_state,stale_descendants:["owner_approval" as const],owner_stop:"APPROVED_GRAPH_AMENDMENT_REQUIRES_OWNER" as const}},current=state.generations.at(-1)!; const r=advanceDecompositionApproval(state,{schema_version:1,kind:"OBSERVE_GRAPH",expected_generation:current.generation,expected_record_digest:current.record_digest},n1,mut); return {s:mut,state:r.state!};}
function amendment(state:DecompositionApprovalStateV1,owner:TrustedDecompositionOwnerContextV1=n1){const current=state.generations.at(-1)!; const base={schema_version:1 as const,kind:"AUTHORIZE_AMENDMENT" as const,expected_generation:current.generation,expected_parent_record_digest:current.record_digest,new_generation:g("a"),new_graph_digest:h("b"),new_candidate_digest:h("c"),new_manifest_digest:h("d"),new_scope_digest:h("e"),prior_record_digests:state.generations.map(x=>x.record_digest),prior_observation_digests:state.invalidation_observations.map(x=>x.observation_digest),evidence_digests:[h("f")]}; return {...base,amendment_authorization_digest:decompositionApprovalDigest({...base,owner})};}
test("PG-04-T006-FC07 amendment appends N+1 and re-enters at candidate",()=>{const {s,state}=invalidated(),a=amendment(state),r=advanceDecompositionApproval(state,a,n1,s); assert.equal(r.code,"ADVANCED"); assert.equal(r.state?.generations.length,state.generations.length+1); assert.deepEqual(r.state?.generations.slice(0,-1),state.generations); assert.equal(r.state?.generations.at(-1)?.status,"REVIEW_PENDING"); assert.equal(r.transition_reentry?.phase,"DECOMPOSITION_CANDIDATE"); assert.equal(r.state?.generations.at(-1)?.approval_digest,null);});
test("PG-04-T006-FC08 scope reduction and history reconciliation are refused",()=>{const {s,state}=invalidated(),reduced={...s,proposed_scope_ids:["n1"]}; assert.equal(advanceDecompositionApproval(state,amendment(state),n1,reduced).code,"AMENDMENT_AUTHORITY_INVALID"); const a={...amendment(state),prior_record_digests:state.generations.slice(1).map(x=>x.record_digest)}; assert.equal(advanceDecompositionApproval(state,a,n1,s).code,"AMENDMENT_AUTHORITY_INVALID");});
test("PG-04-T006-FC09 unauthorized generation reset is refused without mutation",()=>{const {s,state}=invalidated(),a=amendment(state),before=structuredClone(state); const r=advanceDecompositionApproval(state,a,{...n1,owner_id:"other"},s); assert.equal(r.code,"AMENDMENT_AUTHORITY_INVALID"); assert.deepEqual(r.state,before);});
test("PG-04-T006-FC10 missing approval is refused",()=>{const s=scope(),state=initialDecompositionApprovalState(s),a={...approval(state,s,n1),approval_digest:h("0")}; assert.equal(advanceDecompositionApproval(state,a,n1,s).code,"OWNER_APPROVAL_INVALID");});
test("PG-04-T006-FC11 reload is deterministic, frozen, and never authorizes implementation",()=>{const {s,state}=approved(),a={schema_version:1 as const,kind:"OBSERVE_GRAPH" as const,expected_generation:state.generations.at(-1)!.generation,expected_record_digest:state.generations.at(-1)!.record_digest},one=advanceDecompositionApproval(state,a,n1,s),two=advanceDecompositionApproval(structuredClone(state),structuredClone(a),structuredClone(n1),structuredClone(s)); assert.deepEqual(one,two); assert.equal(one.state?.implementation_authorized,false); assert.ok(Object.isFrozen(one)); assert.ok(Object.isFrozen(one.state?.generations));});

test("PG-04-T006 hostile malformed input preserves state",()=>{const s=scope(),state=initialDecompositionApprovalState(s),before=structuredClone(state); assert.equal(advanceDecompositionApproval(state,{...approval(state,s,n1),extra:true},n1,s).code,"MALFORMED_OR_UNKNOWN_FIELD"); assert.deepEqual(state,before);});

test("PG-04-T006 T001 denial and stale authorities have prerequisite precedence",()=>{const s=scope(),state=initialDecompositionApprovalState(s),denied={...s,transition_result:{...s.transition_result,code:"STALE_DERIVATION" as const,advanced:false}}; assert.equal(advanceDecompositionApproval(state,approval(state,s,n1),n1,denied).code,"PREREQUISITE_AUTHORITY_INVALID"); const staleState={...s.transition_state,derived_authorities:{...s.transition_state.derived_authorities,owner_approval:{...s.transition_state.derived_authorities.owner_approval,status:"STALE_DERIVATION" as const}}},stale={...s,transition_state:staleState,transition_result:{...s.transition_result,state:staleState}}; assert.equal(advanceDecompositionApproval(state,approval(state,s,n1),n1,stale).code,"PREREQUISITE_AUTHORITY_INVALID");});

test("PG-04-T006 cyclic product disposition fails closed without throwing",()=>{const s:any=scope(),state=initialDecompositionApprovalState(s),cyclic:any={kind:"REVIEW",round:1,digest:h("a"),reviewer_id:"reviewer-a",candidate_digest:h("b")}; cyclic.candidate_digest=cyclic; s.review_disposition.repair_chains=[cyclic]; assert.doesNotThrow(()=>assert.equal(advanceDecompositionApproval(state,approval(state,scope(),n1),n1,s).code,"MALFORMED_OR_UNKNOWN_FIELD"));});

test("PG-04-T006 missing observed graph cannot emit an unloadable state",()=>{const {s,state}=approved(),mut:any={...s,transition_result:{code:"APPROVED_GRAPH_MUTATED",advanced:false,state:s.transition_state,stale_descendants:["owner_approval"],owner_stop:"APPROVED_GRAPH_AMENDMENT_REQUIRES_OWNER"}}; delete mut.observed_graph_digest; const current=state.generations.at(-1)!; const result=advanceDecompositionApproval(state,{schema_version:1,kind:"OBSERVE_GRAPH",expected_generation:current.generation,expected_record_digest:current.record_digest},n1,mut); assert.equal(result.code,"MALFORMED_OR_UNKNOWN_FIELD"); assert.deepEqual(result.state,state);});

test("PG-04-T006 forked same-generation parent link is rejected",()=>{const {s,state}=approved(),records=structuredClone(state.generations),last:any={...records.at(-1),parent_record_digest:h("f")}; const body={...last}; delete body.record_digest; last.record_digest=decompositionApprovalDigest(body); const fork={...state,generations:[records[0],last]}; assert.equal(advanceDecompositionApproval(fork,{schema_version:1,kind:"OBSERVE_GRAPH",expected_generation:last.generation,expected_record_digest:last.record_digest},n1,s).code,"MALFORMED_OR_UNKNOWN_FIELD");});

test("PG-04-T006 fresh N+1 disposition can approve after structural re-entry",()=>{const {s,state}=invalidated(),a=amendment(state),next=advanceDecompositionApproval(state,a,n1,s),pending=next.state!,reentry={...next.transition_reentry!,derived_authorities:{...next.transition_reentry!.derived_authorities,owner_approval:{...next.transition_reentry!.derived_authorities.owner_approval,status:"ACTIVE" as const},ticket_activation:{...next.transition_reentry!.derived_authorities.ticket_activation,status:"ACTIVE" as const}}},body={schema_version:1 as const,status:"TWO_ROUND_DECOMPOSITION_REVIEW_COMPLETE" as const,generation:a.new_generation,candidate_digest:a.new_candidate_digest,manifest_digest:a.new_manifest_digest,scope_digest:a.new_scope_digest,used:2 as const,reviewers:[{round:1 as const,reviewer_id:"new-a",reviewer_family:"claude",track:"n1" as const},{round:2 as const,reviewer_id:"new-b",reviewer_family:"gemini",track:"enterprise" as const}],repair_chains:[],open_findings:[] as const},base={...s,generation:a.new_generation,graph_digest:a.new_graph_digest,candidate_digest:a.new_candidate_digest,manifest_digest:a.new_manifest_digest,scope_digest:a.new_scope_digest,parent_scope_ids:[...s.proposed_scope_ids],transition_state:reentry,transition_result:{code:"ADVANCED" as const,advanced:true,state:reentry,stale_descendants:[],owner_stop:null},observed_graph_digest:null},replay={...base,review_disposition:s.review_disposition},fresh={...base,review_disposition:{...body,disposition_digest:decompositionReviewDigest(body)}}; assert.equal(advanceDecompositionApproval(pending,approval(pending,replay,n1),n1,replay).code,"OWNER_APPROVAL_INVALID"); assert.equal(advanceDecompositionApproval(pending,approval(pending,fresh,n1),n1,fresh).code,"ADVANCED");});
