import assert from "node:assert/strict";
import test from "node:test";
import { ENGINEERING_STATUS_PROJECTION_MIGRATED_WRITERS_V1, publishEngineeringStatusProjectionV1, rebuildEngineeringStatusProjectionV1, reconcileEngineeringStatusProjectionV1, requireEngineeringStatusAuthorityV1, type EngineeringLifecycleSourceV1, type EngineeringStatusProjectionAuthorityV1, type EngineeringStatusProjectionStoreV1, type EngineeringStatusProjectionV1 } from "../src/spine/engineering_status_projection_v1.js";
import type { AuthoritativeReplayV1Receipt } from "../src/spine/authoritative_replay_v1.js";
import { FileEngineeringStatusProjectionStoreV1 } from "../src/autonomy/project_checkpoint_store.js";
import { mkdtempSync, readdirSync, unlinkSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const H=(c:string)=>c.repeat(64).slice(0,64);
const n1:EngineeringStatusProjectionAuthorityV1={kind:"n1",principal_id:"owner",custody_id:"local",organization_services:"ABSENT"};
const enterprise:EngineeringStatusProjectionAuthorityV1={kind:"enterprise",organization_id:"org",tenant_id:"tenant",actor_id:"alice",role_id:"engineer",custody_id:"vault",isolation_id:"iso",local_owner_substitution:false};
function source(kind:EngineeringLifecycleSourceV1["kind"],authority:EngineeringStatusProjectionAuthorityV1=n1,count=1):EngineeringLifecycleSourceV1{
  const a=authority.kind==="n1"?{kind:"n1" as const,track:"n1" as const,actor_id:authority.principal_id,authority_domain:"local-owner" as const,custody_id:authority.custody_id}:{kind:"enterprise" as const,track:"enterprise" as const,actor_id:authority.actor_id,authority_domain:"organization" as const,custody_id:authority.custody_id,organization_id:authority.organization_id,tenant_id:authority.tenant_id,actor_role_id:authority.role_id,isolation_id:authority.isolation_id};
  const receipt:AuthoritativeReplayV1Receipt={schema:"keep.spine.authoritative-replay-receipt",schema_version:1n,history_id:"run",event_count:BigInt(count),final_sequence:BigInt(count-1),final_event_id:H("a"),final_head_id:H(String(count%10)),witness_id:H("b"),checkpoint_digest:H("c"),codec:"keep.rfc8949-core-deterministic-cbor.v1",codec_version:1n,reducer_identities:[H("d")],interpreter_set_digests:[H("e")],state_digest:H("f"),authority:a,effects_performed:false,projection_authoritative:false,closed:true};
  return {kind,receipt,status:{phase:kind==="goal"?"ARCHITECTURE_AUTHORIZED":"COMPLETE"}};
}
const input=(authority:EngineeringStatusProjectionAuthorityV1=n1)=>({schema_version:1 as const,project_id:authority.kind==="n1"?"project-local":"project-enterprise",run_id:"run",authority,sources:[source("goal",authority),source("decomposition",authority),source("approval",authority)]});
class Store implements EngineeringStatusProjectionStoreV1{value:EngineeringStatusProjectionV1|undefined;load(){return this.value;}compareAndSave(_id:string,expected:string|null,next:EngineeringStatusProjectionV1){if((this.value?.projection_digest??null)!==expected)return false;this.value=next;return true;}}

test("PG-05-T013-FC01 exact W10-W13 inventory",()=>assert.deepEqual(ENGINEERING_STATUS_PROJECTION_MIGRATED_WRITERS_V1,["W10","W11","W12","W13"]));
test("PG-05-T013-FC02 deletion rebuilds byte-identical n1 and enterprise views",()=>{for(const authority of [n1,enterprise]){const a=rebuildEngineeringStatusProjectionV1(input(authority)),b=reconcileEngineeringStatusProjectionV1(input(authority),undefined);assert.equal(a.ok,true);assert.equal(b.ok,true);if(a.ok&&b.ok)assert.deepEqual(b.projection,a.projection);}});
test("PG-05-T013-FC03 a cache claiming a later head is discarded",()=>{const built=rebuildEngineeringStatusProjectionV1(input());assert.equal(built.ok,true);if(!built.ok)return;const forged=structuredClone(built.projection) as any;forged.source_heads[0].event_count=99;const result=reconcileEngineeringStatusProjectionV1(input(),forged);assert.equal(result.ok,true);if(result.ok){assert.equal(result.disposition,"FORGED_REPLACED");assert.deepEqual(result.projection,built.projection);}});
test("PG-05-T013-FC04 projection cannot publish without a closed event commit",()=>{const bad=input();(bad.sources[0] as any).receipt.closed=false;assert.deepEqual(publishEngineeringStatusProjectionV1(bad,new Store(),null),{ok:false,code:"EVENT_COMMIT_REQUIRED"});});
test("PG-05-T013-FC05 a stale process cannot overwrite a newer projection",()=>{const store=new Store();const older=input();assert.equal(publishEngineeringStatusProjectionV1(older,store,null).ok,true);const staleDigest=store.value!.projection_digest;const newer=input();(newer.sources as any)[0]=source("goal",n1,2);assert.equal(publishEngineeringStatusProjectionV1(newer,store,staleDigest).ok,true);assert.deepEqual(publishEngineeringStatusProjectionV1(older,store,staleDigest),{ok:false,code:"STALE_PROJECTION"});});
test("PG-05-T013-FC06 another project, run, or track is refused",()=>{const built=rebuildEngineeringStatusProjectionV1(input());assert.equal(built.ok,true);if(!built.ok)return;assert.deepEqual(reconcileEngineeringStatusProjectionV1({...input(),project_id:"other"},built.projection),{ok:false,code:"TRACK_AUTHORITY_SUBSTITUTION"});const otherRun=input();(otherRun.sources[0] as any).receipt.history_id="other-run";assert.deepEqual(rebuildEngineeringStatusProjectionV1(otherRun),{ok:false,code:"TRACK_AUTHORITY_SUBSTITUTION"});const mixed=input();(mixed.sources as any)[0]=source("goal",enterprise);assert.deepEqual(rebuildEngineeringStatusProjectionV1(mixed),{ok:false,code:"TRACK_AUTHORITY_SUBSTITUTION"});});
test("PG-05-T013-FC07 a surviving projection cannot replace missing history",()=>{const built=rebuildEngineeringStatusProjectionV1(input());assert.equal(built.ok,true);if(!built.ok)return;assert.deepEqual(reconcileEngineeringStatusProjectionV1({...input(),sources:[]},built.projection),{ok:false,code:"HISTORY_REQUIRED"});});
test("PG-05-T013-FC08 projection authority is always forbidden",()=>{const built=rebuildEngineeringStatusProjectionV1(input());assert.equal(built.ok,true);if(built.ok)assert.deepEqual(requireEngineeringStatusAuthorityV1(built.projection),{ok:false,code:"PROJECTION_AUTHORITY_FORBIDDEN"});});
test("PG-05-T013 file cache publishes atomically and reads back exact bytes",()=>{const dir=mkdtempSync(join(tmpdir(),"keep-t013-view-")),store=new FileEngineeringStatusProjectionStoreV1(dir),published=publishEngineeringStatusProjectionV1(input(),store,null);assert.equal(published.ok,true);if(published.ok)assert.deepEqual(store.load("project-local"),published.projection);});
test("PG-05-T013 deleted file cache rebuilds byte-identically",()=>{const dir=mkdtempSync(join(tmpdir(),"keep-t013-delete-")),store=new FileEngineeringStatusProjectionStoreV1(dir),first=publishEngineeringStatusProjectionV1(input(),store,null);assert.equal(first.ok,true);unlinkSync(join(dir,readdirSync(dir)[0]!));assert.equal(store.load("project-local"),undefined);const rebuilt=publishEngineeringStatusProjectionV1(input(),store,null);assert.equal(rebuilt.ok,true);if(first.ok&&rebuilt.ok)assert.deepEqual(rebuilt.projection,first.projection);});
