import test from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { eirDigest } from "../src/eir/canonical.js";

import type { GoalLifecycleRequestV1 } from "../src/autonomy/project_state.js";
import { goalDigest, type AuthorityContextV1, type GoalBodyV1, type GoalScopeAuthorityV1 } from "../src/goal/goal_authority.js";
import { evaluateGoalTransition, GOAL_TRANSITION_PHASES, type ConsequenceGraphV1, type GoalTransitionProposalV1, type GoalTransitionStateV1 } from "../src/goal/goal_transition.js";
import { researchProtocolDigest, type GoalResearchRecordV1, type ResearchProtocolV1 } from "../src/research/goal_research.js";
import type { AuthoritativeReplayV1Event, AuthoritativeReplayV1Result } from "../src/spine/authoritative_replay_v1.js";
import { EventEnvelopeV1CodecIdentity, EventEnvelopeV1Encode, EventEnvelopeV1Schema, type EventEnvelopeV1Value } from "../src/spine/event_envelope_v1.js";
import { EventAdmissionV1HeadDigestDomain } from "../src/spine/event_admission_v1.js";
import { goalAuthorityRequestDigestV1, nextGoalAuthorityEventV1, reconstructGoalAuthorityEventsV1, rejectLegacyGoalMutationV1, type GoalAuthorityEventV1, type GoalAuthorityReplayBundleV1 } from "../src/spine/goal_authority_events_v1.js";

const H=(c:string)=>c.repeat(64), D=H("d"), E=H("e"), NOW="2026-09-03T00:00:00Z";
const stable=(v:unknown):unknown=>Array.isArray(v)?v.map(stable):v!==null&&typeof v==="object"?Object.fromEntries(Object.keys(v as Record<string,unknown>).sort().map(k=>[k,stable((v as Record<string,unknown>)[k])])):v;
const digest=(v:unknown)=>createHash("sha256").update(JSON.stringify(stable(v))).digest("hex");
const clone=<T>(v:T):T=>JSON.parse(JSON.stringify(v)) as T;
function graph():ConsequenceGraphV1{return {questions:["q"],scope_ids:["scope"],sources:["source"],mechanisms:["mechanism"],consequences:["consequence"],edges:[{from:"q",to:"mechanism"},{from:"scope",to:"mechanism"},{from:"source",to:"mechanism"},{from:"source",to:"consequence"},{from:"mechanism",to:"consequence"}],owner_stops:[]}}

function fixture(kind:"n1"|"enterprise"="n1"):GoalLifecycleRequestV1 {
  const body:GoalBodyV1={schema_version:1,goal_id:`goal-${kind}`,outcome:"event authority",authority:kind==="n1"?{kind:"owner",owner_id:"owner",custody_id:"custody"}:{kind:"organization",organization_id:"org",actor_id:"alice",role_id:"maintainer",separation_policy_id:"sod"},scope_ids:["S1"],track_obligations:{n1:["local"],enterprise:["organization"],parity:["integrity"],equivalent:false},assumptions:["fixed"],finish_conditions:["authorized"],non_goals:[{statement:"no execution",retained_by:["PG-05"]}],research_contract:{current:["current"],historical:["history"],cross_disciplinary:["transfer"]},adverse_evidence_questions:["failure"],falsifiers:["scope loss"],dependency_closures:[{id:"PG-03",digest:D}],created_by:kind==="n1"?"owner":"alice",created_at:NOW,executable:false};
  const goal_digest=goalDigest(body);
  const authority:AuthorityContextV1=kind==="n1"?{kind:"n1",goal_digest,decision_id:"decision",decided_at:NOW,principal_id:"owner",authority_domain:"local-owner",verification_result:"PASS",custody_id:"custody"}:{kind:"enterprise",goal_digest,decision_id:"decision",decided_at:NOW,principal_id:"alice",authority_domain:"organization",verification_result:"PASS",organization_id:"org",role_id:"maintainer",separation_policy_id:"sod",evidence_digest:E};
  const scope:GoalScopeAuthorityV1={known_scope_ids:["S1"],required_scope_ids:["S1"],required_track_obligations:{n1:["local"],enterprise:["organization"],parity:["integrity"]},dependency_closures:{"PG-03":D}};
  const protocol:ResearchProtocolV1={schema_version:1,goal_digest,predecessor_digest:D,questions:{current:"current?",historical:"history?",cross_disciplinary:"transfer?"},inclusion_rules:["primary"],exclusion_rules:["none"],freshness_policies:{mutable_current_months:3,versioned_standard:"IDENTITY",immutable_local:"IDENTITY"},expected_adverse_evidence:["failure"],falsifiers:["scope loss"],required_consequence_classes:["goal_question","scope","architecture","requirement","threat","test_oracle"]};
  const row=(id:string,lane:"current"|"historical"|"cross-disciplinary",source_class:"mutable-current"|"versioned-standard"|"immutable-local",evidence_stance:"SUPPORTS"|"MIXED"|"ADVERSE")=>({row_id:id,lane,locator:`https://example.test/${id}`,query:id,candidate:id,observation:id,observed_at:"2026-06-03T00:00:00Z",observed_identity:id,source_class,disposition:"SELECTED" as const,disposition_reason:"selected",uncertainty:"bounded",evidence_stance});
  const rows=[row("c","current","mutable-current","SUPPORTS"),row("h","historical","immutable-local","MIXED"),row("x","cross-disciplinary","versioned-standard","ADVERSE")];
  const classes=["goal_question","scope","architecture","requirement","threat","test_oracle"] as const;
  const research:GoalResearchRecordV1={schema_version:1,goal_digest,predecessor_digest:D,protocol_digest:researchProtocolDigest(protocol),rows,adverse_evidence:["failure"],falsifiers:["scope loss"],consequences:classes.map((c,i)=>({consequence_id:`k${i}`,class:c,statement:c,mechanism:"event authority",source_row_ids:[rows[i%3]!.row_id]})),executable:false};
  const protocol_digest=researchProtocolDigest(protocol),research_digest=digest(research);
  let state:GoalTransitionStateV1={schema_version:1,phase:"GOAL_PROPOSED",active_head_digest:goal_digest,ancestor_digests:{goal:goal_digest,protocol:protocol_digest,research:research_digest},descendants:{protocol:{digest:H("1"),depends_on:["goal"],status:"ACTIVE"},research:{digest:H("2"),depends_on:["protocol"],status:"ACTIVE"},semantic_admission:{digest:H("3"),depends_on:["research"],status:"ACTIVE"},architecture:{digest:H("4"),depends_on:["semantic_admission"],status:"ACTIVE"},decomposition:{digest:H("5"),depends_on:["architecture"],status:"ACTIVE"},owner_approval:{digest:H("6"),depends_on:["decomposition"],status:"ACTIVE"},tickets:{digest:H("7"),depends_on:["owner_approval"],status:"ACTIVE"}},downstream_vets_consumed:0};
  const initial=clone(state),transitions:GoalTransitionProposalV1[]=[];
  for(let i=1;i<GOAL_TRANSITION_PHASES.length;i++){
    const to=GOAL_TRANSITION_PHASES[i]!;const p:GoalTransitionProposalV1={schema_version:1,from_phase:state.phase,to_phase:to,expected_active_head_digest:state.active_head_digest,next_head_digest:H("0"),required_ancestor_digests:{...state.ancestor_digests},consequence_graph:graph(),semantic_admission:null,trusted_reviewer_ids:["reviewer"],expected_ticket_digest:H("a"),expected_policy_digest:H("b"),expected_evidence_digest:H("c"),authority_verdict:"PASS",supersedes:i===3?"research":null,authority_context:kind==="n1"?{kind:"n1",principal_id:"owner",custody_id:"custody",organization_services:"ABSENT"}:{kind:"enterprise",organization_id:"org",actor_id:"alice",role_id:"maintainer",separation_policy_id:"sod",local_owner_substitution:false},downstream_vet:null};
    if(to==="RESEARCH_SEMANTIC_PASS")p.semantic_admission={schema_version:1,ticket_digest:H("a"),round:1,research_digest:p.required_ancestor_digests.research!,author_family:"OpenAI",reviewer_family:"Anthropic",reviewer_id:"reviewer",policy_digest:H("b"),evidence_digest:H("c"),reviewed_at:NOW,verdict:"PASS"};
    p.next_head_digest=to==="GOAL_ADMITTED"?goal_digest:to==="RESEARCH_PROTOCOL_FROZEN"?protocol_digest:to==="RESEARCH_CANDIDATE"||to==="RESEARCH_STRUCTURAL_PASS"?research_digest:to==="RESEARCH_SEMANTIC_PASS"?digest(p.semantic_admission):digest({goal_digest,protocol_digest,research_digest,semantic_digest:transitions.at(-1)!.next_head_digest,consequence_graph:p.consequence_graph});
    transitions.push(p);const r=evaluateGoalTransition(state,p);if(!r.advanced)throw new Error(r.code);state=r.state;
  }
  return {schema_version:1,goal_candidate:{body,goal_digest},authority_context:authority,scope_authority:scope,research_protocol:protocol,research_record:research,observed_at:NOW,current_source_identities:Object.fromEntries(rows.map(r=>[r.locator,r.observed_identity])),transition_state:initial,transitions,executable:false};
}

function envelope(history:string,index:number,event:GoalAuthorityEventV1,kind:"n1"|"enterprise",predecessor_event_id:string|null,predecessor_head_id:string|null) {
  const proposal:EventEnvelopeV1Value={schema:EventEnvelopeV1Schema,schema_version:1n,codec:EventEnvelopeV1CodecIdentity,codec_version:1n,history_id:history,sequence:BigInt(index),predecessor_event_id,predecessor_head_id,event_type:event.operation==="goal-admitted"?"goal.admitted":"goal.transitioned",actor_id:kind==="n1"?"owner":"alice",authority_domain:kind==="n1"?"local-owner":"organization",track:kind,payload:{domain_json:JSON.stringify(event)},effect_correlation:null};
  const encoded=EventEnvelopeV1Encode(proposal);if(!encoded.ok)throw new Error(encoded.code);const head=eirDigest(EventAdmissionV1HeadDigestDomain,{history_id:history,sequence:BigInt(index),event_id:encoded.event_digest,predecessor_head_id});
  return {row:{proposal,target_version:1n,interpreter_set_digest:H("c")} satisfies AuthoritativeReplayV1Event,event_id:encoded.event_digest,head_id:head};
}
function bundle(request:GoalLifecycleRequestV1,count:number,mutate?:(event:GoalAuthorityEventV1)=>void):GoalAuthorityReplayBundleV1 {
  const kind=(request.authority_context as AuthorityContextV1).kind,history=`history-${kind}`,events:AuthoritativeReplayV1Event[]=[];let eventId:string|null=null,headId:string|null=null;
  for(let i=0;i<count;i++){const event=nextGoalAuthorityEventV1(history,request,i)!;if(i===count-1)mutate?.(event as GoalAuthorityEventV1);const built=envelope(history,i,event,kind,eventId,headId);events.push(built.row);eventId=built.event_id;headId=built.head_id}
  const authority=kind==="n1"?{kind:"n1" as const,track:"n1" as const,actor_id:"owner",authority_domain:"local-owner",custody_id:"custody"}:{kind:"enterprise" as const,track:"enterprise" as const,actor_id:"alice",authority_domain:"organization",custody_id:"org-custody",organization_id:"org",tenant_id:"tenant",actor_role_id:"maintainer",isolation_id:"sod"};
  const replay={ok:true,state_bytes:new Uint8Array(),result_digest:H("d"),receipt:{schema:"keep.spine.authoritative-replay-receipt",schema_version:1n,history_id:history,event_count:BigInt(events.length),final_sequence:BigInt(events.length-1),final_event_id:eventId!,final_head_id:headId!,witness_id:H("1"),checkpoint_digest:H("2"),codec:EventEnvelopeV1CodecIdentity,codec_version:1n,reducer_identities:[],interpreter_set_digests:[],state_digest:H("3"),authority,effects_performed:false,projection_authoritative:false,closed:true}} as AuthoritativeReplayV1Result;
  return {events,replay};
}

test("PG-05-T010-FC01 inventory remains exact",()=>{const expected=new Map([["src/goal/goal_authority.ts","0a98259896f3859a5b224a1fb1b6187764fae2ab5dd86ad87788c8da1dbfde1a"],["src/goal/goal_transition.ts","f5770a103b8e3c5d50885401c7dd267ba1b2973436fed27763683c83eae87325"]]);for(const [path,sha] of expected)assert.equal(createHash("sha256").update(readFileSync(path)).digest("hex"),sha);assert.ok(readFileSync("src/autonomy/autonomy_loop.ts","utf8").includes("reconstructGoalAuthorityEventsV1"))});
test("PG-05-T010-FC02 local lifecycle reconstructs without status",()=>{const r=fixture(),b=bundle(r,8),x=reconstructGoalAuthorityEventsV1("history-n1",r,b);assert.equal(x.ok,true);if(x.ok)assert.equal(x.artifact?.code,"ARCHITECTURE_AUTHORIZED")});
test("PG-05-T010-FC03 organization lifecycle retains tenant and attribution",()=>{const r=fixture("enterprise"),x=reconstructGoalAuthorityEventsV1("history-enterprise",r,bundle(r,8));assert.equal(x.ok,true)});
test("PG-05-T010-FC04 mutable status is not an input to reconstruction",()=>{const r=fixture(),x=reconstructGoalAuthorityEventsV1("history-n1",r,bundle(r,4));assert.equal(x.ok,true);if(x.ok)assert.equal(x.artifact?.next_transition_index,2)});
test("PG-05-T010-FC05 omitted invalidation refuses",()=>{const r=fixture(),x=reconstructGoalAuthorityEventsV1("history-n1",r,bundle(r,5,e=>{if(e.transition_result)e.transition_result.stale_descendants=[]}));assert.deepEqual(x,{ok:false,code:"INCOMPLETE_GOAL_HISTORY"})});
test("PG-05-T010-FC06 track substitution refuses",()=>{const r=fixture(),b=bundle(r,2),proof=b.replay as Extract<AuthoritativeReplayV1Result,{ok:true}>;(proof.receipt as {authority:unknown}).authority={kind:"enterprise"};assert.deepEqual(reconstructGoalAuthorityEventsV1("history-n1",r,b),{ok:false,code:"TRACK_AUTHORITY_SUBSTITUTION"})});
test("PG-05-T010-FC07 direct legacy mutation is rejected",()=>{assert.deepEqual(rejectLegacyGoalMutationV1(),{ok:false,code:"LEGACY_GOAL_MUTATION_REJECTED"});assert.equal(goalAuthorityRequestDigestV1(fixture()).length,64)});
