import test from "node:test";
import assert from "node:assert/strict";
import { evaluateGoalTransition, GOAL_TRANSITION_PHASES, type ConsequenceGraphV1, type GoalTransitionPhase, type GoalTransitionProposalV1, type GoalTransitionStateV1 } from "../src/goal/goal_transition.js";

const H=(c:string)=>c.repeat(64), TICKET=H("a"), POLICY=H("b"), EVIDENCE=H("c"), RESEARCH=H("d");
const clone=<T>(v:T):T=>JSON.parse(JSON.stringify(v)) as T;
const graph=():ConsequenceGraphV1=>({questions:["q"],scope_ids:["scope"],sources:["source"],mechanisms:["mechanism"],consequences:["consequence"],edges:[{from:"q",to:"mechanism"},{from:"scope",to:"mechanism"},{from:"source",to:"mechanism"},{from:"source",to:"consequence"},{from:"mechanism",to:"consequence"}],owner_stops:[]});
const descendants=()=>({
  protocol:{digest:H("1"),depends_on:["goal"],status:"ACTIVE" as const},research:{digest:H("2"),depends_on:["protocol"],status:"ACTIVE" as const},semantic_admission:{digest:H("3"),depends_on:["research"],status:"ACTIVE" as const},architecture:{digest:H("4"),depends_on:["semantic_admission"],status:"ACTIVE" as const},decomposition:{digest:H("5"),depends_on:["architecture"],status:"ACTIVE" as const},owner_approval:{digest:H("6"),depends_on:["decomposition"],status:"ACTIVE" as const},tickets:{digest:H("7"),depends_on:["owner_approval"],status:"ACTIVE" as const},
});
function state(phase:GoalTransitionPhase="GOAL_PROPOSED"):GoalTransitionStateV1{return {schema_version:1,phase,active_head_digest:H("8"),ancestor_digests:{goal:H("9"),protocol:H("1"),research:RESEARCH},descendants:descendants(),downstream_vets_consumed:0}}
function proposal(s:GoalTransitionStateV1,to:GoalTransitionPhase=GOAL_TRANSITION_PHASES[GOAL_TRANSITION_PHASES.indexOf(s.phase)+1]!):GoalTransitionProposalV1{return {schema_version:1,from_phase:s.phase,to_phase:to,expected_active_head_digest:s.active_head_digest,next_head_digest:H("e"),required_ancestor_digests:{goal:s.ancestor_digests.goal!,protocol:s.ancestor_digests.protocol!,research:s.ancestor_digests.research!},consequence_graph:graph(),semantic_admission:null,trusted_reviewer_ids:["reviewer-1"],expected_ticket_digest:TICKET,expected_policy_digest:POLICY,expected_evidence_digest:EVIDENCE,authority_verdict:"PASS",supersedes:null,authority_context:{kind:"n1",principal_id:"owner",custody_id:"custody",organization_services:"ABSENT"},downstream_vet:null}}
function semantic(p:GoalTransitionProposalV1,verdict:"PASS"|"REJECT"="PASS"){p.semantic_admission={schema_version:1,ticket_digest:TICKET,round:1,research_digest:p.required_ancestor_digests.research!,author_family:"OpenAI",reviewer_family:"Anthropic",reviewer_id:"reviewer-1",policy_digest:POLICY,evidence_digest:EVIDENCE,reviewed_at:"2026-09-03T00:00:00Z",verdict}}
function denied(s:GoalTransitionStateV1,p:unknown,code:string){const before=JSON.stringify(s),r=evaluateGoalTransition(s,p);assert.equal(r.code,code);assert.equal(r.advanced,false);assert.equal(JSON.stringify(r.state),before);assert.equal(JSON.stringify(s),before)}

test("PG-03-T003-FC01 orphan question",()=>{const s=state(),p=proposal(s);p.consequence_graph.edges=p.consequence_graph.edges.filter(e=>e.from!=="q");denied(s,p,"CONSEQUENCE_ORPHAN")});
test("PG-03-T003-FC02 orphan scope",()=>{const s=state(),p=proposal(s);p.consequence_graph.edges=p.consequence_graph.edges.filter(e=>e.from!=="scope");denied(s,p,"CONSEQUENCE_ORPHAN")});
test("PG-03-T003-FC03 orphan mechanism",()=>{const s=state(),p=proposal(s);p.consequence_graph.edges=p.consequence_graph.edges.filter(e=>e.from!=="mechanism");denied(s,p,"CONSEQUENCE_ORPHAN")});
test("PG-03-T003-FC04 orphan consequence",()=>{const s=state(),p=proposal(s);p.consequence_graph.edges=p.consequence_graph.edges.filter(e=>!(e.to==="consequence"&&e.from==="source"));denied(s,p,"CONSEQUENCE_ORPHAN")});
test("PG-03-T003-FC05 orphan source row",()=>{const s=state(),p=proposal(s);p.consequence_graph.sources.push("orphan-source");denied(s,p,"CONSEQUENCE_ORPHAN")});
test("PG-03-T003-FC06 missing semantic admission",()=>{const s=state("RESEARCH_STRUCTURAL_PASS"),p=proposal(s);denied(s,p,"SEMANTIC_ADMISSION_MISSING")});
test("PG-03-T003-FC07 forged semantic admission",()=>{for(const mutation of [(p:GoalTransitionProposalV1)=>{semantic(p);p.semantic_admission!.reviewer_family="OpenAI"},(p:GoalTransitionProposalV1)=>{semantic(p);p.semantic_admission!.research_digest=H("f")}]){const s=state("RESEARCH_STRUCTURAL_PASS"),p=proposal(s);mutation(p);denied(s,p,"SEMANTIC_ADMISSION_INVALID")}});
test("PG-03-T003-FC08 rejected semantic admission",()=>{const s=state("RESEARCH_STRUCTURAL_PASS"),p=proposal(s);semantic(p,"REJECT");denied(s,p,"SEMANTIC_ADMISSION_REJECTED")});
test("PG-03-T003-FC09 semantic receipt reuse",()=>{const s=state("RESEARCH_STRUCTURAL_PASS"),p=proposal(s);semantic(p);p.semantic_admission!.research_digest=H("f");denied(s,p,"SEMANTIC_ADMISSION_INVALID")});
test("PG-03-T003-FC10 downstream vet receipt reuse",()=>{for(const [receipt,receiptRound] of [[H("f"),1],[TICKET,2]] as const){const s=state(),p=proposal(s);p.downstream_vet={ticket_digest:TICKET,round:1,receipt_ticket_digest:receipt,receipt_round:receiptRound};denied(s,p,"OWNER_DECISION")}});
test("PG-03-T003-FC11 third downstream vet",()=>{const s=state();s.downstream_vets_consumed=2;const p=proposal(s);p.downstream_vet={ticket_digest:TICKET,round:3,receipt_ticket_digest:TICKET,receipt_round:3};const r=evaluateGoalTransition(s,p);assert.equal(r.code,"OWNER_DECISION");assert.equal(r.vet_consumed,false);assert.equal(r.state.downstream_vets_consumed,2)});
test("PG-03-T003-FC12 goal supersession descendants",()=>{const s=state(),p=proposal(s);p.supersedes="goal";const r=evaluateGoalTransition(s,p);assert.equal(r.code,"ADVANCED");assert.deepEqual(r.stale_descendants,["protocol","research","semantic_admission","architecture","decomposition","owner_approval","tickets"]);assert.ok(Object.values(r.state.descendants).every(d=>d.status==="STALE_DERIVATION"))});
test("PG-03-T003-FC13 protocol supersession descendants",()=>{const s=state("GOAL_ADMITTED"),p=proposal(s);p.supersedes="protocol";const r=evaluateGoalTransition(s,p);assert.deepEqual(r.stale_descendants,["research","semantic_admission","architecture","decomposition","owner_approval","tickets"]);assert.equal(r.state.descendants.protocol.status,"ACTIVE")});
test("PG-03-T003-FC14 research supersession descendants",()=>{const s=state("RESEARCH_PROTOCOL_FROZEN"),p=proposal(s);p.supersedes="research";const r=evaluateGoalTransition(s,p);assert.deepEqual(r.stale_descendants,["semantic_admission","architecture","decomposition","owner_approval","tickets"]);assert.equal(r.state.descendants.protocol.status,"ACTIVE");assert.equal(r.state.descendants.research.status,"ACTIVE")});
test("PG-03-T003-FC15 rejected proposal inert",()=>{const s=state(),p=proposal(s);p.authority_verdict="REJECT";denied(s,p,"AUTHORITY_REJECTED")});
test("PG-03-T003-FC16 simultaneous faults ordered",()=>{const s=state(),p=proposal(s) as GoalTransitionProposalV1&{unknown?:boolean};p.unknown=true;p.to_phase="ARCHITECTURE_AUTHORIZED";p.expected_active_head_digest=H("f");denied(s,p,"MALFORMED_OR_UNKNOWN_FIELD")});
test("PG-03-T003-FC17 positive full transition chain",()=>{let s=state();for(let i=1;i<GOAL_TRANSITION_PHASES.length;i++){const p=proposal(s);if(p.to_phase==="RESEARCH_SEMANTIC_PASS")semantic(p);const r=evaluateGoalTransition(s,p);assert.equal(r.code,"ADVANCED");assert.equal(r.advanced,true);s=r.state}assert.equal(s.phase,"ARCHITECTURE_AUTHORIZED")});

const skips:[GoalTransitionPhase,GoalTransitionPhase][]=[];for(let i=0;i<GOAL_TRANSITION_PHASES.length;i++)for(let j=i+2;j<GOAL_TRANSITION_PHASES.length;j++)skips.push([GOAL_TRANSITION_PHASES[i]!,GOAL_TRANSITION_PHASES[j]!]);
assert.equal(skips.length,15);
skips.forEach(([from,to],i)=>test(`PG-03-T003-FC${String(i+18).padStart(2,"0")} forward skip ${from} to ${to}`,()=>{const s=state(from),p=proposal(s,to);denied(s,p,"ILLEGAL_PHASE_EDGE")}));
test("PG-03-T003-FC33 exact boundary recovery resumes once",()=>{const original=state(),recovered=JSON.parse(JSON.stringify(original)) as GoalTransitionStateV1;assert.deepEqual(recovered,original);const p=proposal(recovered),first=evaluateGoalTransition(recovered,p);assert.equal(first.code,"ADVANCED");assert.equal(first.state.phase,"GOAL_ADMITTED");denied(first.state,p,"ILLEGAL_PHASE_EDGE")});

test("n=1 and enterprise retain distinct caller authority while sharing transition integrity",()=>{const local=proposal(state());assert.equal(evaluateGoalTransition(state(),local).code,"ADVANCED");const enterprise=proposal(state());enterprise.authority_context={kind:"enterprise",organization_id:"org",actor_id:"alice",role_id:"maintainer",separation_policy_id:"sod",local_owner_substitution:false};assert.equal(evaluateGoalTransition(state(),enterprise).code,"ADVANCED");const substituted=clone(enterprise) as GoalTransitionProposalV1&{authority_context:{local_owner_substitution:boolean}};substituted.authority_context.local_owner_substitution=true;denied(state(),substituted,"MALFORMED_OR_UNKNOWN_FIELD")});
test("vet rounds advance exactly once in order and cannot skip",()=>{let s=state();const skipped=proposal(s);skipped.downstream_vet={ticket_digest:TICKET,round:2,receipt_ticket_digest:TICKET,receipt_round:2};denied(s,skipped,"OWNER_DECISION");for(const round of [1,2] as const){const p=proposal(s);p.downstream_vet={ticket_digest:TICKET,round,receipt_ticket_digest:TICKET,receipt_round:round};const r=evaluateGoalTransition(s,p);assert.equal(r.code,"ADVANCED");assert.equal(r.vet_consumed,true);assert.equal(r.state.downstream_vets_consumed,round);s={...r.state,phase:"GOAL_PROPOSED"}}});
test("invalidation traverses pre-stale nodes and reports only newly stale descendants",()=>{const s=state();s.descendants.semantic_admission.status="STALE_DERIVATION";s.descendants.protocol.status="STALE_DERIVATION";const p=proposal(s);p.supersedes="research";const r=evaluateGoalTransition(s,p);assert.deepEqual(r.stale_descendants,["architecture","decomposition","owner_approval","tickets"]);assert.equal(r.state.descendants.semantic_admission.status,"STALE_DERIVATION");assert.equal(r.stale_descendants.includes("protocol"),false)});
test("a stale phase prerequisite cannot advance but its parent can rebuild it",()=>{const stale=state("RESEARCH_PROTOCOL_FROZEN");stale.descendants.protocol.status="STALE_DERIVATION";denied(stale,proposal(stale),"STALE_DERIVATION");const rebuilding=state("GOAL_ADMITTED");rebuilding.descendants.protocol.status="STALE_DERIVATION";const r=evaluateGoalTransition(rebuilding,proposal(rebuilding));assert.equal(r.code,"ADVANCED");assert.equal(r.state.descendants.protocol.status,"ACTIVE")});
test("a stale transitive phase ancestor cannot be bypassed by a refreshed child",()=>{for(const phase of ["RESEARCH_CANDIDATE","RESEARCH_STRUCTURAL_PASS","RESEARCH_SEMANTIC_PASS"] as const){const s=state(phase);s.descendants.protocol.status="STALE_DERIVATION";const p=proposal(s);if(p.to_phase==="RESEARCH_SEMANTIC_PASS")semantic(p);denied(s,p,"STALE_DERIVATION")}});
