import test from "node:test";
import assert from "node:assert/strict";
import { admitGoal, goalDigest, type AdmittedGoalAuthorityV1, type AuthorityContextV1, type GoalBodyV1, type GoalScopeAuthorityV1 } from "../src/goal/goal_authority.js";

const D = "d".repeat(64), E = "e".repeat(64);
const scope: GoalScopeAuthorityV1 = { known_scope_ids:["ES-S001","ES-S002"], required_scope_ids:["ES-S001","ES-S002"], required_track_obligations:{n1:["local"],enterprise:["organization"],parity:["same-integrity"]}, dependency_closures:{"PG-02":D} };
function body(kind: "n1"|"enterprise" = "n1"): GoalBodyV1 { return {
  schema_version:1, goal_id:"goal-1", outcome:"A complete observable result",
  authority:kind === "n1" ? {kind:"owner",owner_id:"owner-1",custody_id:"custody-1"} : {kind:"organization",organization_id:"org-1",actor_id:"alice",role_id:"maintainer",separation_policy_id:"sod-1"},
  scope_ids:["ES-S001","ES-S002"], track_obligations:{n1:["local"],enterprise:["organization"],parity:["same-integrity"],equivalent:false}, assumptions:["clock injected"], finish_conditions:["all fixed cases pass"], non_goals:[{statement:"no execution",retained_by:["PG-04"]}], research_contract:{current:["current"],historical:["historical"],cross_disciplinary:["assurance"]}, adverse_evidence_questions:["what falsifies this"], falsifiers:["scope loss"], dependency_closures:[{id:"PG-02",digest:D}], created_by:"owner-1", created_at:"2026-09-03T00:00:00Z", executable:false,
}; }
const context = (b: GoalBodyV1): AuthorityContextV1 => b.authority.kind === "owner" ? {kind:"n1",goal_digest:goalDigest(b),decision_id:"decision-1",decided_at:"2026-09-03T00:00:01Z",principal_id:b.authority.owner_id,authority_domain:"local-owner",verification_result:"PASS",custody_id:b.authority.custody_id} : {kind:"enterprise",goal_digest:goalDigest(b),decision_id:"decision-1",decided_at:"2026-09-03T00:00:01Z",principal_id:b.authority.actor_id,authority_domain:"organization",verification_result:"PASS",organization_id:b.authority.organization_id,role_id:b.authority.role_id,separation_policy_id:b.authority.separation_policy_id,evidence_digest:E};
const candidate = (b: GoalBodyV1): Record<string,unknown> => ({body:b,goal_digest:goalDigest(b)});
const clone = <T>(value: T): T => JSON.parse(JSON.stringify(value)) as T;
const denied = (value: ReturnType<typeof admitGoal>, code: string) => { assert.equal(value.admitted,false); if(!value.admitted) assert.equal(value.denial,code); };

test("PG-03-T001-FC01 unknown body field is refused first",()=>{const b={...body(),x_unknown:true}; denied(admitGoal(null,{body:b,goal_digest:"x"},null,scope),"MALFORMED_OR_UNKNOWN_FIELD");});
test("PG-03-T001-FC02 display projection is never authority",()=>denied(admitGoal(null,{kind:"goal-display",goal_id:"goal-1",title:"title",summary:"summary",goal_digest:D},null,scope),"TITLE_OR_SUMMARY_NOT_AUTHORITY"));
test("PG-03-T001-FC03 digest mismatch is refused",()=>{const b=body(); const c=candidate(b); b.finish_conditions=["changed"]; denied(admitGoal(null,c,context(b),scope),"GOAL_IDENTITY_MISMATCH");});
test("PG-03-T001-FC04 candidate-supplied authority cannot replace trusted context",()=>{const b=body(); denied(admitGoal(null,{...candidate(b),authority_context:context(b)},null,scope),"AUTHORITY_CONTEXT_INVALID");});
test("PG-03-T001-FC05 unknown scope is refused",()=>{const b=body(); b.scope_ids.push("ES-UNKNOWN"); denied(admitGoal(null,candidate(b),context(b),scope),"UNKNOWN_SCOPE_ID");});
test("PG-03-T001-FC06 scope removal requires owner",()=>{const b=body(); b.scope_ids=["ES-S001"]; denied(admitGoal(null,candidate(b),context(b),scope),"SCOPE_REDUCTION_REQUIRES_OWNER");});
test("PG-03-T001-FC07 obligation reclassification requires owner",()=>{const b=body(); b.track_obligations.n1=["optional-local"]; denied(admitGoal(null,candidate(b),context(b),scope),"SCOPE_REDUCTION_REQUIRES_OWNER");});
test("PG-03-T001-FC08 track equivalence requires owner",()=>{const b=clone(body()) as unknown as Record<string,unknown>; (b.track_obligations as Record<string,unknown>).equivalent=true; const raw=b as unknown as GoalBodyV1; denied(admitGoal(null,{body:b,goal_digest:goalDigest(raw)},context(raw),scope),"SCOPE_REDUCTION_REQUIRES_OWNER");});
test("PG-03-T001-FC09 n1 refuses organization ceremony",()=>{const b=body(); const enterprise=context(body("enterprise")); denied(admitGoal(null,candidate(b),{...enterprise,goal_digest:goalDigest(b)},scope),"N1_ENTERPRISE_CEREMONY_FORBIDDEN");});
test("PG-03-T001-FC10 enterprise refuses local-owner substitution",()=>{const b=body("enterprise"); const local=context(body()); denied(admitGoal(null,candidate(b),{...local,goal_digest:goalDigest(b)},scope),"ENTERPRISE_AUTHORITY_REQUIRED");});
test("PG-03-T001-FC11 same tag cannot substitute other-track identity",()=>{const b=body("enterprise"); const ctx=context(b); assert.equal(ctx.kind,"enterprise"); denied(admitGoal(null,candidate(b),{...ctx,principal_id:"owner-1",authority_domain:"organization"},scope),"TRACK_AUTHORITY_SUBSTITUTION");});
test("PG-03-T001-FC12 dependency closure is exact",()=>{const b=body(); b.dependency_closures=[]; denied(admitGoal(null,candidate(b),context(b),scope),"DEPENDENCY_CLOSURE_MISSING");});
test("PG-03-T001-FC13 goals cannot authorize execution or tickets",()=>{const b=clone(body()) as unknown as Record<string,unknown>; b.executable=true; const raw=b as unknown as GoalBodyV1; denied(admitGoal(null,{body:b,goal_digest:goalDigest(raw)},context(raw),scope),"GOAL_CANNOT_AUTHORIZE_EXECUTION"); const clean=body(); denied(admitGoal(null,{...candidate(clean),ticket_authority:{}},context(clean),scope),"GOAL_CANNOT_AUTHORIZE_EXECUTION");});
test("PG-03-T001-FC14 n1 admits immutable non-executable authority",()=>{const b=body(), before=JSON.stringify(b), result=admitGoal(null,candidate(b),context(b),scope); assert.equal(result.admitted,true); assert.equal(JSON.stringify(b),before); if(result.admitted){assert.equal(result.authority.executable,false); assert.equal(Object.isFrozen(result.authority.body),true);}});
test("PG-03-T001-FC15 enterprise admits attributed organization authority",()=>{const b=body("enterprise"), result=admitGoal(null,candidate(b),context(b),scope); assert.equal(result.admitted,true); if(result.admitted) assert.equal(result.authority.authority_context.kind,"enterprise");});
test("PG-03-T001-FC16 boundary recovery is byte-identical and exactly-once",()=>{const b=body(), first=admitGoal(null,candidate(b),context(b),scope); assert.equal(first.admitted,true); if(!first.admitted)return; const recovered=JSON.parse(JSON.stringify(first.authority)) as AdmittedGoalAuthorityV1; assert.equal(JSON.stringify(recovered),JSON.stringify(first.authority)); const resumed=admitGoal(recovered,candidate(b),context(b),scope); assert.equal(resumed.admitted,true); if(resumed.admitted) assert.equal(resumed.authority.goal_digest,recovered.goal_digest);});
test("PG-03-T001-FC17 incomplete non-display body preserves caller and prior",()=>{const valid=body(), admitted=admitGoal(null,candidate(valid),context(valid),scope); assert.equal(admitted.admitted,true); if(!admitted.admitted)return; const incomplete={...body()} as Partial<GoalBodyV1>; delete incomplete.finish_conditions; const call={body:incomplete,goal_digest:D}, beforeCall=JSON.stringify(call), beforePrevious=JSON.stringify(admitted.authority); denied(admitGoal(admitted.authority,call,context(valid),scope),"INCOMPLETE_GOAL_BODY"); assert.equal(JSON.stringify(call),beforeCall); assert.equal(JSON.stringify(admitted.authority),beforePrevious);});
