import test from "node:test";
import assert from "node:assert/strict";
import { admitGoal, goalDigest, type AdmittedGoalAuthorityV1, type GoalBodyV1 } from "../src/goal/goal_authority.js";
import { admitGoalResearch } from "../src/research/tri_research_admission.js";
import { researchProtocolDigest, type GoalResearchRecordV1, type ResearchProtocolV1 } from "../src/research/goal_research.js";

const D="d".repeat(64), E="e".repeat(64), NOW="2026-09-03T00:00:00Z";
function goal(kind:"n1"|"enterprise"="n1"): AdmittedGoalAuthorityV1 {
  const body:GoalBodyV1={schema_version:1,goal_id:`research-${kind}`,outcome:"admit exact research",authority:kind==="n1"?{kind:"owner",owner_id:"owner",custody_id:"custody"}:{kind:"organization",organization_id:"org",actor_id:"alice",role_id:"maintainer",separation_policy_id:"sod"},scope_ids:["ES-S002","ES-S004"],track_obligations:{n1:["local"],enterprise:["organization"],parity:["same rigor"],equivalent:false},assumptions:["clock injected"],finish_conditions:["research admitted"],non_goals:[{statement:"no execution",retained_by:["PG-04"]}],research_contract:{current:["q-current"],historical:["q-history"],cross_disciplinary:["q-cross"]},adverse_evidence_questions:["what fails"],falsifiers:["scope loss"],dependency_closures:[{id:"PG-03-T001",digest:D}],created_by:kind==="n1"?"owner":"alice",created_at:NOW,executable:false};
  const digest=goalDigest(body),context=kind==="n1"?{kind:"n1" as const,goal_digest:digest,decision_id:"d",decided_at:NOW,principal_id:"owner",authority_domain:"local-owner" as const,verification_result:"PASS" as const,custody_id:"custody"}:{kind:"enterprise" as const,goal_digest:digest,decision_id:"d",decided_at:NOW,principal_id:"alice",authority_domain:"organization" as const,verification_result:"PASS" as const,organization_id:"org",role_id:"maintainer",separation_policy_id:"sod",evidence_digest:E};
  const result=admitGoal(null,{body,goal_digest:digest},context,{known_scope_ids:["ES-S002","ES-S004"],required_scope_ids:["ES-S002","ES-S004"],required_track_obligations:{n1:["local"],enterprise:["organization"],parity:["same rigor"]},dependency_closures:{"PG-03-T001":D}}); if(!result.admitted)throw new Error("goal fixture refused"); return result.authority;
}
function fixture(authority=goal()) {
  const protocol:ResearchProtocolV1={schema_version:1,goal_digest:authority.goal_digest,predecessor_digest:D,questions:{current:"frontier mechanism?",historical:"historical failure?",cross_disciplinary:"assurance transfer?"},inclusion_rules:["primary evidence"],exclusion_rules:["no unattributed summary"],freshness_policies:{mutable_current_months:3,versioned_standard:"IDENTITY",immutable_local:"IDENTITY"},expected_adverse_evidence:["scope loss"],falsifiers:["simpler equal mechanism"],required_consequence_classes:["goal_question","scope","architecture","requirement","threat","test_oracle"]};
  const row=(id:string,lane:"current"|"historical"|"cross-disciplinary",source_class:"mutable-current"|"versioned-standard"|"immutable-local",stance:"SUPPORTS"|"ADVERSE"|"MIXED")=>({row_id:id,lane,locator:`https://e.example/${id}`,query:`query-${id}`,candidate:`candidate-${id}`,observation:`observation-${id}`,observed_at:"2026-06-03T00:00:00Z",observed_identity:`identity-${id}`,source_class,disposition:"SELECTED" as const,disposition_reason:`reason-${id}`,uncertainty:`uncertainty-${id}`,evidence_stance:stance});
  const rows=[row("c","current","mutable-current","SUPPORTS"),row("h","historical","immutable-local","MIXED"),row("x","cross-disciplinary","versioned-standard","ADVERSE")];
  const consequences=(['goal_question','scope','architecture','requirement','threat','test_oracle'] as const).map((kind,i)=>({consequence_id:`k${i}`,class:kind,statement:`${kind} consequence`,mechanism:"per-source admission",source_row_ids:[rows[i%3]!.row_id]}));
  const record:GoalResearchRecordV1={schema_version:1,goal_digest:authority.goal_digest,predecessor_digest:D,protocol_digest:researchProtocolDigest(protocol),rows,adverse_evidence:["adverse result"],falsifiers:["falsifier"],consequences,executable:false};
  const identities=Object.fromEntries(rows.map((r)=>[r.locator,r.observed_identity])); return {authority,protocol,record,identities};
}
const clone=<T>(v:T):T=>JSON.parse(JSON.stringify(v)) as T;
const denied=(r:ReturnType<typeof admitGoalResearch>,code:string)=>{assert.equal(r.admitted,false);if(!r.admitted)assert.equal(r.denial,code);};

test("PG-03-T002-FC01 missing current lane",()=>{const f=fixture();f.record.rows=f.record.rows.filter(r=>r.lane!=="current");denied(admitGoalResearch(f.authority,f.protocol,f.record,NOW,f.identities),"RESEARCH_LANE_MISSING");});
test("PG-03-T002-FC02 copied cross-lane row",()=>{const f=fixture();Object.assign(f.record.rows[1]!,{locator:f.record.rows[0]!.locator,query:f.record.rows[0]!.query,disposition:f.record.rows[0]!.disposition});f.identities[f.record.rows[0]!.locator]=f.record.rows[0]!.observed_identity;f.record.rows[1]!.observed_identity=f.record.rows[0]!.observed_identity;denied(admitGoalResearch(f.authority,f.protocol,f.record,NOW,f.identities),"SOURCE_LEDGER_INCOMPLETE");});
test("PG-03-T002-FC03 generic records have no reciprocal consequences",()=>{const f=fixture();const orphan={...f.record.rows[0]!,row_id:"orphan",locator:"https://e.example/orphan",query:"query-orphan",observed_identity:"identity-orphan"};f.record.rows.push(orphan);f.identities[orphan.locator]=orphan.observed_identity;denied(admitGoalResearch(f.authority,f.protocol,f.record,NOW,f.identities),"CONSEQUENCE_ORPHAN");});
test("PG-03-T002-FC04 consequence-free source",()=>{const f=fixture();f.record.consequences=f.record.consequences.filter(c=>c.class!=="architecture");denied(admitGoalResearch(f.authority,f.protocol,f.record,NOW,f.identities),"CONSEQUENCE_ORPHAN");});
test("PG-03-T002-FC05 missing or superseded protocol",()=>{const f=fixture();f.record.protocol_digest="0".repeat(64);denied(admitGoalResearch(f.authority,f.protocol,f.record,NOW,f.identities),"RESEARCH_PROTOCOL_MISSING");});
test("PG-03-T002-FC06 grouped mutable locators",()=>{for(const locator of ["https://a.example, https://b.example","https://a.example https://b.example","https://a.example;https://b.example"]){const f=fixture();f.record.rows[0]!.locator=locator;denied(admitGoalResearch(f.authority,f.protocol,f.record,NOW,f.identities),"SOURCE_LEDGER_INCOMPLETE");}});
test("PG-03-T002-FC07 mutable current equality is fresh and inputs stay exact",()=>{const f=fixture(),before=JSON.stringify(f);const r=admitGoalResearch(f.authority,f.protocol,f.record,"2026-09-03T00:00:00Z",f.identities);assert.equal(r.admitted,true);assert.equal(JSON.stringify(f),before);});
test("PG-03-T002-FC08 mutable current beyond three calendar months is stale",()=>{const f=fixture();denied(admitGoalResearch(f.authority,f.protocol,f.record,"2026-09-03T00:00:00.001Z",f.identities),"SOURCE_STALE");});
test("PG-03-T002-FC09 unchanged versioned standard ignores elapsed months",()=>{const f=fixture();f.record.rows[0]!.source_class="versioned-standard";const r=admitGoalResearch(f.authority,f.protocol,f.record,"2028-09-03T00:00:00Z",f.identities);assert.equal(r.admitted,true);});
test("PG-03-T002-FC10 changed standard identity is stale",()=>{const f=fixture();f.identities[f.record.rows[2]!.locator]="new-version";denied(admitGoalResearch(f.authority,f.protocol,f.record,NOW,f.identities),"SOURCE_STALE");});
test("PG-03-T002-FC11 immutable local exact identity ignores time",()=>{const f=fixture();f.record.rows[0]!.source_class="immutable-local";const r=admitGoalResearch(f.authority,f.protocol,f.record,"2030-01-01T00:00:00Z",f.identities);assert.equal(r.admitted,true);});
test("PG-03-T002-FC12 changed immutable identity is stale",()=>{const f=fixture();f.identities[f.record.rows[1]!.locator]="wrong-commit";denied(admitGoalResearch(f.authority,f.protocol,f.record,NOW,f.identities),"SOURCE_STALE");});
test("PG-03-T002-FC13 silent exclusion is refused",()=>{for(const field of ["disposition","disposition_reason","uncertainty","evidence_stance"] as const){const f=fixture();delete (f.record.rows[0] as unknown as Record<string,unknown>)[field];denied(admitGoalResearch(f.authority,f.protocol,f.record,NOW,f.identities),"ADVERSE_EVIDENCE_MISSING");}});
test("PG-03-T002-FC14 support-only evidence is refused",()=>{const f=fixture();f.record.rows.forEach(r=>r.evidence_stance="SUPPORTS");denied(admitGoalResearch(f.authority,f.protocol,f.record,NOW,f.identities),"ADVERSE_EVIDENCE_MISSING");});
test("PG-03-T002-FC15 authority survives exact recovery and resumes once",()=>{const f=fixture(goal("enterprise")),first=admitGoalResearch(f.authority,f.protocol,f.record,NOW,f.identities);assert.equal(first.admitted,true);if(!first.admitted)return;const recovered=clone(first.authority);assert.deepEqual(recovered,first.authority);const resumed=admitGoalResearch(f.authority,f.protocol,recovered,NOW,f.identities);assert.equal(resumed.admitted,false,"an admitted envelope is not a candidate record and cannot advance twice");});
