import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { createHash, createPrivateKey, generateKeyPairSync, sign } from "node:crypto";
import { chmodSync, chownSync, existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, symlinkSync, unlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

import type { GoalLifecycleRequestV1 } from "../src/autonomy/project_state.js";
import type { DecompositionApprovalAuthorityEventV1 } from "../src/decomposition/decomposition_approval_events_v1.js";
import type { DecompositionAuthorityEventV1 } from "../src/decomposition/decomposition_review_events_v1.js";
import { goalDigest, type AuthorityContextV1, type GoalBodyV1, type GoalScopeAuthorityV1 } from "../src/goal/goal_authority.js";
import { evaluateGoalTransition, GOAL_TRANSITION_PHASES, type ConsequenceGraphV1, type GoalTransitionProposalV1, type GoalTransitionStateV1 } from "../src/goal/goal_transition.js";
import { researchProtocolDigest, type GoalResearchRecordV1, type ResearchProtocolV1 } from "../src/research/goal_research.js";
import type { EventEnvelopeV1Value } from "../src/spine/event_envelope_v1.js";
import { decodeCanonical, eirDigest, encodeCanonical } from "../src/eir/canonical.js";
import { CommittedHeadV1CheckpointDigestDomain } from "../src/spine/committed_head_v1.js";
import { AuthoritativeAppendV1HistoryPath } from "../src/spine/authoritative_append_v1.js";
import { nextGoalAuthorityEventV1, type GoalAuthorityEventV1 } from "../src/spine/goal_authority_events_v1.js";
import { recoverN1EventAuthorityJourneyV1, requireEnterpriseFromN1JourneyV1, runN1EventAuthorityJourneyV1, type N1EventAuthorityJourneyInputV1 } from "../src/spine/n1_event_authority_integration_v1.js";
import { resultInput } from "./decomposition_result_events_v1.test.js";

const H=(c:string)=>c.repeat(64),D=H("d"),NOW="2026-09-03T00:00:00Z";
const stable=(v:unknown):unknown=>Array.isArray(v)?v.map(stable):v!==null&&typeof v==="object"?Object.fromEntries(Object.keys(v as Record<string,unknown>).sort().map(k=>[k,stable((v as Record<string,unknown>)[k])])):v;
const digest=(v:unknown)=>createHash("sha256").update(JSON.stringify(stable(v))).digest("hex");
const graph=():ConsequenceGraphV1=>({questions:["q"],scope_ids:["scope"],sources:["source"],mechanisms:["mechanism"],consequences:["consequence"],edges:[{from:"q",to:"mechanism"},{from:"scope",to:"mechanism"},{from:"source",to:"mechanism"},{from:"source",to:"consequence"},{from:"mechanism",to:"consequence"}],owner_stops:[]});

function goalRequest():GoalLifecycleRequestV1{
  const body:GoalBodyV1={schema_version:1,goal_id:"t015-local",outcome:"replay local authority",authority:{kind:"owner",owner_id:"owner",custody_id:"local"},scope_ids:["S1"],track_obligations:{n1:["local"],enterprise:["organization"],parity:["integrity"],equivalent:false},assumptions:["fixed"],finish_conditions:["authorized"],non_goals:[{statement:"no execution",retained_by:["PG-05"]}],research_contract:{current:["current"],historical:["history"],cross_disciplinary:["transfer"]},adverse_evidence_questions:["failure"],falsifiers:["scope loss"],dependency_closures:[{id:"PG-03",digest:D}],created_by:"owner",created_at:NOW,executable:false};
  const goal_digest=goalDigest(body),authority:AuthorityContextV1={kind:"n1",goal_digest,decision_id:"decision",decided_at:NOW,principal_id:"owner",authority_domain:"local-owner",verification_result:"PASS",custody_id:"local"},scope:GoalScopeAuthorityV1={known_scope_ids:["S1"],required_scope_ids:["S1"],required_track_obligations:{n1:["local"],enterprise:["organization"],parity:["integrity"]},dependency_closures:{"PG-03":D}},protocol:ResearchProtocolV1={schema_version:1,goal_digest,predecessor_digest:D,questions:{current:"current?",historical:"history?",cross_disciplinary:"transfer?"},inclusion_rules:["primary"],exclusion_rules:["none"],freshness_policies:{mutable_current_months:3,versioned_standard:"IDENTITY",immutable_local:"IDENTITY"},expected_adverse_evidence:["failure"],falsifiers:["scope loss"],required_consequence_classes:["goal_question","scope","architecture","requirement","threat","test_oracle"]};
  const row=(id:string,lane:"current"|"historical"|"cross-disciplinary",source_class:"mutable-current"|"versioned-standard"|"immutable-local",evidence_stance:"SUPPORTS"|"MIXED"|"ADVERSE")=>({row_id:id,lane,locator:`https://example.test/${id}`,query:id,candidate:id,observation:id,observed_at:"2026-06-03T00:00:00Z",observed_identity:id,source_class,disposition:"SELECTED" as const,disposition_reason:"selected",uncertainty:"bounded",evidence_stance}),rows=[row("c","current","mutable-current","SUPPORTS"),row("h","historical","immutable-local","MIXED"),row("x","cross-disciplinary","versioned-standard","ADVERSE")],classes=["goal_question","scope","architecture","requirement","threat","test_oracle"] as const,research:GoalResearchRecordV1={schema_version:1,goal_digest,predecessor_digest:D,protocol_digest:researchProtocolDigest(protocol),rows,adverse_evidence:["failure"],falsifiers:["scope loss"],consequences:classes.map((c,i)=>({consequence_id:`k${i}`,class:c,statement:c,mechanism:"event authority",source_row_ids:[rows[i%3]!.row_id]})),executable:false};
  const protocol_digest=researchProtocolDigest(protocol),research_digest=digest(research);let state:GoalTransitionStateV1={schema_version:1,phase:"GOAL_PROPOSED",active_head_digest:goal_digest,ancestor_digests:{goal:goal_digest,protocol:protocol_digest,research:research_digest},descendants:{protocol:{digest:H("1"),depends_on:["goal"],status:"ACTIVE"},research:{digest:H("2"),depends_on:["protocol"],status:"ACTIVE"},semantic_admission:{digest:H("3"),depends_on:["research"],status:"ACTIVE"},architecture:{digest:H("4"),depends_on:["semantic_admission"],status:"ACTIVE"},decomposition:{digest:H("5"),depends_on:["architecture"],status:"ACTIVE"},owner_approval:{digest:H("6"),depends_on:["decomposition"],status:"ACTIVE"},tickets:{digest:H("7"),depends_on:["owner_approval"],status:"ACTIVE"}},downstream_vets_consumed:0},initial=structuredClone(state),transitions:GoalTransitionProposalV1[]=[];
  for(let i=1;i<GOAL_TRANSITION_PHASES.length;i++){const to=GOAL_TRANSITION_PHASES[i]!,p:GoalTransitionProposalV1={schema_version:1,from_phase:state.phase,to_phase:to,expected_active_head_digest:state.active_head_digest,next_head_digest:H("0"),required_ancestor_digests:{...state.ancestor_digests},consequence_graph:graph(),semantic_admission:null,trusted_reviewer_ids:["reviewer"],expected_ticket_digest:H("a"),expected_policy_digest:H("b"),expected_evidence_digest:H("c"),authority_verdict:"PASS",supersedes:i===3?"research":null,authority_context:{kind:"n1",principal_id:"owner",custody_id:"local",organization_services:"ABSENT"},downstream_vet:null};if(to==="RESEARCH_SEMANTIC_PASS")p.semantic_admission={schema_version:1,ticket_digest:H("a"),round:1,research_digest:p.required_ancestor_digests.research!,author_family:"OpenAI",reviewer_family:"Anthropic",reviewer_id:"reviewer",policy_digest:H("b"),evidence_digest:H("c"),reviewed_at:NOW,verdict:"PASS"};p.next_head_digest=to==="GOAL_ADMITTED"?goal_digest:to==="RESEARCH_PROTOCOL_FROZEN"?protocol_digest:to==="RESEARCH_CANDIDATE"||to==="RESEARCH_STRUCTURAL_PASS"?research_digest:to==="RESEARCH_SEMANTIC_PASS"?digest(p.semantic_admission):digest({goal_digest,protocol_digest,research_digest,semantic_digest:transitions.at(-1)!.next_head_digest,consequence_graph:p.consequence_graph});transitions.push(p);const next=evaluateGoalTransition(state,p);if(!next.advanced)throw new Error(next.code);state=next.state;}
  return {schema_version:1,goal_candidate:{body,goal_digest},authority_context:authority,scope_authority:scope,research_protocol:protocol,research_record:research,observed_at:NOW,current_source_identities:Object.fromEntries(rows.map(r=>[r.locator,r.observed_identity])),transition_state:initial,transitions,executable:false};
}

const domainEvents=<T>(bundle:{events:readonly {proposal:unknown}[]},runId:string):T[]=>bundle.events.map(row=>({...JSON.parse((((row.proposal as EventEnvelopeV1Value).payload as {domain_json:string}).domain_json)) as T&{run_id:string},run_id:runId}));
function journey(label:string):N1EventAuthorityJourneyInputV1{
  const root=mkdtempSync(join(tmpdir(),`keep-t015-${label}-`)),run_id=`t015-${label}`,goal_request=goalRequest(),goal_events:GoalAuthorityEventV1[]=[];for(let i=0;;i++){const event=nextGoalAuthorityEventV1(run_id,goal_request,i);if(event===null)break;goal_events.push(event)}
  const prior=resultInput("n1"),{privateKey,publicKey}=generateKeyPairSync("ed25519");return {schema_version:1,project_id:`project-${label}`,run_id,data_directory:join(root,"data"),history_directory:join(root,"history"),witness_directory:join(root,"witness"),owner_id:"owner",custody_id:"local",organization_services:"ABSENT",witness_private_key:privateKey.export({type:"pkcs8",format:"pem"}).toString(),witness_public_key:publicKey.export({type:"spki",format:"pem"}).toString(),goal_request,goal_events,review_events:domainEvents<DecompositionAuthorityEventV1>(prior.review_history,run_id),approval_events:domainEvents<DecompositionApprovalAuthorityEventV1>(prior.approval_history,run_id),activation:{...prior.activation,authority:{kind:"n1",owner_id:"owner",custody_id:"local",organization_services:"ABSENT"}}};
}
const rootOf=(input:N1EventAuthorityJourneyInputV1)=>join(input.data_directory,"..");
const recoveryInput=(input:N1EventAuthorityJourneyInputV1):N1EventAuthorityJourneyInputV1=>{const {witness_private_key:_,...recovery}=input;return recovery};

test("PG-05-T015-FC01/02/03 local histories survive projection deletion and fresh-process recovery",async()=>{const input=journey("recover");try{const first=await runN1EventAuthorityJourneyV1(input);assert.equal(first.code,"N1_EVENT_AUTHORITY_COMPLETE");assert.equal(first.receipt?.track,"n1");assert.equal(readdirSync(join(input.data_directory,"projections")).length,1);rmSync(input.data_directory,{recursive:true,force:true});const recovered=await recoverN1EventAuthorityJourneyV1(recoveryInput(input));assert.equal(recovered.code,"N1_EVENT_AUTHORITY_RECOVERED");assert.equal(recovered.receipt?.receipt_digest,first.receipt?.receipt_digest)}finally{rmSync(rootOf(input),{recursive:true,force:true})}});
test("PG-05-T015-FC04 local-owner identity substitution is refused",async()=>{const input=journey("identity");try{assert.equal((await runN1EventAuthorityJourneyV1({...input,activation:{...input.activation,authority:{kind:"n1",owner_id:"other",custody_id:"local",organization_services:"ABSENT"}}})).code,"TRACK_AUTHORITY_SUBSTITUTION")}finally{rmSync(rootOf(input),{recursive:true,force:true})}});
test("PG-05-T015-FC05 a disposable projection cannot replace authority history",async()=>{const input=journey("projection");try{assert.equal((await runN1EventAuthorityJourneyV1(input)).ok,true);rmSync(input.history_directory,{recursive:true,force:true});rmSync(input.witness_directory,{recursive:true,force:true});assert.equal((await recoverN1EventAuthorityJourneyV1(recoveryInput(input))).code,"RESTART_AUTHORITY_REQUIRED");assert.equal(existsSync(input.history_directory),false);assert.equal(existsSync(input.witness_directory),false)}finally{rmSync(rootOf(input),{recursive:true,force:true})}});
test("SG-01-T001-C05 witnessed acknowledgements cannot become an empty history",async()=>{const input=journey("witness-without-history");try{assert.equal((await runN1EventAuthorityJourneyV1(input)).ok,true);rmSync(AuthoritativeAppendV1HistoryPath(join(input.history_directory,"goal"),input.run_id),{recursive:true,force:true});assert.equal((await recoverN1EventAuthorityJourneyV1(recoveryInput(input))).code,"RESTART_AUTHORITY_REQUIRED")}finally{rmSync(rootOf(input),{recursive:true,force:true})}});
test("PG-05-T015-FC06 local success cannot satisfy enterprise authority",async()=>{const input=journey("enterprise");try{const result=await runN1EventAuthorityJourneyV1(input);assert.equal(result.ok,true);assert.deepEqual(requireEnterpriseFromN1JourneyV1(result.receipt!),{ok:false,code:"TRACK_AUTHORITY_SUBSTITUTION"})}finally{rmSync(rootOf(input),{recursive:true,force:true})}});
test("SG-01-T001-C06 substituted product build refuses before mutation",async()=>{const input=journey("build-substitution");try{const result=await runN1EventAuthorityJourneyV1({...input,expected_product_build_identity:"substituted"});assert.equal(result.code,"N1_EVENT_HISTORY_INVALID");assert.equal(result.receipt,null);assert.equal(readdirSync(rootOf(input)).length,0)}finally{rmSync(rootOf(input),{recursive:true,force:true})}});
test("SG-01-T001-C02 two OS witness publishers admit exactly one successor",async()=>{const root=mkdtempSync(join(tmpdir(),"keep-t001-cas-")),history=join(root,"history"),witness=join(root,"witness"),barrier=join(root,"start"),historyId="c02-history",{privateKey,publicKey}=generateKeyPairSync("ed25519"),privatePem=privateKey.export({type:"pkcs8",format:"pem"}).toString(),publicPem=publicKey.export({type:"spki",format:"pem"}).toString();mkdirSync(history,{mode:0o700});mkdirSync(witness,{mode:0o700});const checkpoints=["a","b"].map(branch=>Buffer.from(encodeCanonical({history_id:historyId,sequence:0n,prior_witness_digest:null,branch})).toString("base64")),worker=`import {existsSync} from "node:fs";const {FileN1CommittedHeadWitnessV1}=await import(process.env.WITNESS_MODULE);const {FileSystemLock}=await import(process.env.LOCK_MODULE);while(!existsSync(process.env.BARRIER))await new Promise(r=>setTimeout(r,2));const w=new FileN1CommittedHeadWitnessV1(process.env.WITNESS_ROOT,new FileSystemLock(process.env.LOCK_ROOT),process.env.PUBLIC_KEY,process.env.PRIVATE_KEY);const r=await w.compareAndPersist(null,new Uint8Array(Buffer.from(process.env.CHECKPOINT,"base64")));process.stdout.write(JSON.stringify(r.ok?{ok:true}:{ok:false,code:r.code}));`,run=(checkpoint:string)=>new Promise<{ok:boolean;code?:string}>((resolve,reject)=>{const child=spawn(process.execPath,["--input-type=module","-e",worker],{env:{...process.env,WITNESS_MODULE:new URL("../src/spine/n1_event_authority_integration_v1.js",import.meta.url).href,LOCK_MODULE:new URL("../src/lock/lock.js",import.meta.url).href,BARRIER:barrier,WITNESS_ROOT:witness,LOCK_ROOT:join(history,".locks"),PUBLIC_KEY:publicPem,PRIVATE_KEY:privatePem,CHECKPOINT:checkpoint}});let stdout="",stderr="";child.stdout.on("data",b=>stdout+=b);child.stderr.on("data",b=>stderr+=b);child.on("error",reject);child.on("close",code=>code===0?resolve(JSON.parse(stdout) as {ok:boolean;code?:string}):reject(new Error(stderr)))});try{const pending=checkpoints.map(run);writeFileSync(barrier,"go",{mode:0o600});const results=await Promise.all(pending);assert.equal(results.filter(r=>r.ok).length,1);assert.deepEqual(results.filter(r=>!r.ok),[{ok:false,code:"WITNESS_CONFLICT"}])}finally{rmSync(root,{recursive:true,force:true})}});
test("SG-01-T001-C09 two signed acknowledgements at one sequence refuse as a witness fork",async()=>{const input=journey("fork");try{assert.equal((await runN1EventAuthorityJourneyV1(input)).ok,true);const stream="approval",dir=join(input.witness_directory,stream,createHash("sha256").update("keep.n1-witness/v1\0").update(input.run_id).digest("hex")),name=readdirSync(dir).sort().at(-1)!,stored=decodeCanonical(readFileSync(join(dir,name))) as Record<string,unknown>,checkpoint=decodeCanonical(stored.checkpoint_bytes as Uint8Array) as Record<string,unknown>,alternative=encodeCanonical({...checkpoint,record_digest:"f".repeat(64)} as never),checkpointDigest=eirDigest(CommittedHeadV1CheckpointDigestDomain,alternative),rawKey=input.witness_private_key!,privateKey=createPrivateKey(typeof rawKey==="string"?rawKey:Buffer.from(rawKey)),signature=new Uint8Array(sign(null,alternative,privateKey)),sequence=(checkpoint.sequence as bigint).toString(16).padStart(16,"0"),bytes=encodeCanonical({schema:"keep.n1-witness-ack",schema_version:1n,history_id:input.run_id,checkpoint_bytes:alternative,checkpoint_digest:checkpointDigest,signature});writeFileSync(join(dir,`${sequence}-${checkpointDigest}.ack`),bytes,{mode:0o600});const {witness_private_key:_,...recovery}=input;assert.equal((await recoverN1EventAuthorityJourneyV1(recovery)).code,"N1_WITNESS_FORK")}finally{rmSync(rootOf(input),{recursive:true,force:true})}});
test("SG-01-T001-C08 hostile filesystem shapes refuse without further history mutation",async()=>{const variants:[string,(ack:string,history:string)=>void][]=[["malformed-name",(_ack,history)=>writeFileSync(join(history,"not-an-ack"),"x",{mode:0o600})],["malformed-ack",ack=>writeFileSync(ack,"bad")],["wrong-mode",ack=>chmodSync(ack,0o644)],["symlink",ack=>{unlinkSync(ack);symlinkSync("/dev/null",ack)}],["over-limit",ack=>writeFileSync(ack,Buffer.alloc(8_388_609))],["malformed-frame",(_ack,history)=>{const record=readdirSync(history).filter(n=>n.endsWith(".record")).sort().at(-1)!;writeFileSync(join(history,record),"bad") }]];if(typeof process.getuid==="function"&&process.getuid()===0)variants.push(["wrong-owner",ack=>chownSync(ack,65534,65534)]);for(const [label,attack] of variants){const input=journey(`hostile-${label}`);try{assert.equal((await runN1EventAuthorityJourneyV1(input)).ok,true);const ackDir=join(input.witness_directory,"approval",createHash("sha256").update("keep.n1-witness/v1\0").update(input.run_id).digest("hex")),ack=join(ackDir,readdirSync(ackDir).sort().at(-1)!),history=label==="malformed-name"?ackDir:AuthoritativeAppendV1HistoryPath(join(input.history_directory,"approval"),input.run_id);attack(ack,history);const before=readdirSync(AuthoritativeAppendV1HistoryPath(join(input.history_directory,"approval"),input.run_id)).sort();const {witness_private_key:_,...recovery}=input;assert.equal((await recoverN1EventAuthorityJourneyV1(recovery)).code,"RESTART_AUTHORITY_REQUIRED",label);assert.deepEqual(readdirSync(AuthoritativeAppendV1HistoryPath(join(input.history_directory,"approval"),input.run_id)).sort(),before,label)}finally{rmSync(rootOf(input),{recursive:true,force:true})}}});
test("PG-05-T015-FC08 n=1 rejects an enterprise-service prerequisite",async()=>{const input=journey("ceremony");try{assert.equal((await runN1EventAuthorityJourneyV1({...input,organization_services:"REQUIRED"})).code,"N1_ENTERPRISE_CEREMONY_FORBIDDEN")}finally{rmSync(rootOf(input),{recursive:true,force:true})}});
