import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createHash } from "node:crypto";
import { buildAutonomyLoop } from "../src/autonomy/autonomy_loop.js";
import { InMemoryProjectCheckpointStore } from "../src/autonomy/project_checkpoint_store.js";
import type { GoalLifecycleArtifactV1, GoalLifecycleRequestV1 } from "../src/autonomy/project_state.js";
import { goalDigest, type AuthorityContextV1, type GoalBodyV1, type GoalScopeAuthorityV1 } from "../src/goal/goal_authority.js";
import { evaluateGoalTransition, GOAL_TRANSITION_PHASES, type ConsequenceGraphV1, type GoalTransitionProposalV1, type GoalTransitionStateV1 } from "../src/goal/goal_transition.js";
import { researchProtocolDigest, type GoalResearchRecordV1, type ResearchProtocolV1 } from "../src/research/goal_research.js";
import { Spine } from "../src/spine/spine.js";
import { FileSpineStore } from "../src/spine/store.js";
import { SchemaRegistry } from "../src/spine/upcaster.js";
import { InProcessLock } from "../src/lock/lock.js";
import type { GoalAuthorityEventPortV1, GoalAuthorityEventV1, GoalAuthorityReplayBundleV1 } from "../src/spine/goal_authority_events_v1.js";
import type { AuthoritativeReplayV1Event, AuthoritativeReplayV1Result } from "../src/spine/authoritative_replay_v1.js";
import { EventEnvelopeV1CodecIdentity, EventEnvelopeV1Schema, type EventEnvelopeV1Value } from "../src/spine/event_envelope_v1.js";
import { EventEnvelopeV1Encode } from "../src/spine/event_envelope_v1.js";
import { EventAdmissionV1HeadDigestDomain } from "../src/spine/event_admission_v1.js";
import { eirDigest } from "../src/eir/canonical.js";
import { InMemoryEngineeringStatusProjectionStoreV1, type EngineeringStatusProjectionStoreV1 } from "../src/spine/engineering_status_projection_v1.js";

const H=(c:string)=>c.repeat(64), D=H("d"), E=H("e"), NOW="2026-09-03T00:00:00Z";
type MutableRequest={-readonly [K in keyof GoalLifecycleRequestV1]:GoalLifecycleRequestV1[K]};
const clone=<T>(v:T):T=>JSON.parse(JSON.stringify(v)) as T;
const stable=(v:unknown):unknown=>Array.isArray(v)?v.map(stable):v!==null&&typeof v==="object"?Object.fromEntries(Object.keys(v as Record<string,unknown>).sort().map(k=>[k,stable((v as Record<string,unknown>)[k])])):v;
const digestValue=(v:unknown)=>createHash("sha256").update(JSON.stringify(stable(v))).digest("hex");
function spine(){return new Spine(new FileSpineStore(mkdtempSync(join(tmpdir(),"keep-goal-path-"))),new InProcessLock(),new SchemaRegistry())}
class TestGoalPort implements GoalAuthorityEventPortV1 {
  private readonly rows=new Map<string,AuthoritativeReplayV1Event[]>();
  async load(id:string){const rows=this.rows.get(id);return rows?this.bundle(id,rows):null}
  async appendAndReplay(id:string,event:GoalAuthorityEventV1){const rows=this.rows.get(id)??[],kind=(event.artifact.request.authority_context as AuthorityContextV1).kind,index=rows.length,prior=index===0?null:this.coordinates(id,rows).at(-1)!;const proposal:EventEnvelopeV1Value={schema:EventEnvelopeV1Schema,schema_version:1n,codec:EventEnvelopeV1CodecIdentity,codec_version:1n,history_id:id,sequence:BigInt(index),predecessor_event_id:prior?.event_id??null,predecessor_head_id:prior?.head_id??null,event_type:event.operation==="goal-admitted"?"goal.admitted":"goal.transitioned",actor_id:kind==="n1"?"owner":"alice",authority_domain:kind==="n1"?"local-owner":"organization",track:kind,payload:{domain_json:JSON.stringify(event)},effect_correlation:null};rows.push({proposal,target_version:1n,interpreter_set_digest:H("c")});this.rows.set(id,rows);return this.bundle(id,rows)}
  private coordinates(id:string,rows:AuthoritativeReplayV1Event[]){let prior:string|null=null;return rows.map((row,index)=>{const encoded=EventEnvelopeV1Encode(row.proposal);if(!encoded.ok)throw new Error(encoded.code);const head_id=eirDigest(EventAdmissionV1HeadDigestDomain,{history_id:id,sequence:BigInt(index),event_id:encoded.event_digest,predecessor_head_id:prior});prior=head_id;return{event_id:encoded.event_digest,head_id}})}
  private bundle(id:string,rows:AuthoritativeReplayV1Event[]):GoalAuthorityReplayBundleV1{const event=JSON.parse(((rows[0]!.proposal as EventEnvelopeV1Value).payload as {domain_json:string}).domain_json) as GoalAuthorityEventV1,context=event.artifact.request.authority_context as AuthorityContextV1,authority=context.kind==="n1"?{kind:"n1" as const,track:"n1" as const,actor_id:context.principal_id,authority_domain:"local-owner",custody_id:context.custody_id}:{kind:"enterprise" as const,track:"enterprise" as const,actor_id:context.principal_id,authority_domain:"organization",custody_id:"org-custody",organization_id:context.organization_id,tenant_id:"tenant",actor_role_id:context.role_id,isolation_id:context.separation_policy_id},tail=this.coordinates(id,rows).at(-1)!;const replay={ok:true,state_bytes:new Uint8Array(),result_digest:H("d"),receipt:{schema:"keep.spine.authoritative-replay-receipt",schema_version:1n,history_id:id,event_count:BigInt(rows.length),final_sequence:BigInt(rows.length-1),final_event_id:tail.event_id,final_head_id:tail.head_id,witness_id:H("1"),checkpoint_digest:H("2"),codec:EventEnvelopeV1CodecIdentity,codec_version:1n,reducer_identities:[],interpreter_set_digests:[],state_digest:H("3"),authority,effects_performed:false,projection_authoritative:false,closed:true}} as AuthoritativeReplayV1Result;return{events:rows,replay}}
}
const ports=new WeakMap<InMemoryProjectCheckpointStore,TestGoalPort>();
function loop(store=new InMemoryProjectCheckpointStore(),called={value:0},engineeringStatusProjections?:EngineeringStatusProjectionStoreV1){let goalAuthorityEvents=ports.get(store);if(!goalAuthorityEvents){goalAuthorityEvents=new TestGoalPort();ports.set(store,goalAuthorityEvents)}return buildAutonomyLoop({spine:spine(),checkpoints:store,goalAuthorityEvents,...(engineeringStatusProjections?{engineeringStatusProjections}:{}),solve:async()=>{called.value++;throw new Error("structured goal authority reached solve")}})}
function graph():ConsequenceGraphV1{return {questions:["q"],scope_ids:["scope"],sources:["source"],mechanisms:["mechanism"],consequences:["consequence"],edges:[{from:"q",to:"mechanism"},{from:"scope",to:"mechanism"},{from:"source",to:"mechanism"},{from:"source",to:"consequence"},{from:"mechanism",to:"consequence"}],owner_stops:[]}}
function fixture(kind:"n1"|"enterprise"="n1"):MutableRequest{
  const body:GoalBodyV1={schema_version:1,goal_id:`integrated-${kind}`,outcome:"authorize architecture without execution",authority:kind==="n1"?{kind:"owner",owner_id:"owner",custody_id:"custody"}:{kind:"organization",organization_id:"org",actor_id:"alice",role_id:"maintainer",separation_policy_id:"sod"},scope_ids:["S1","S2"],track_obligations:{n1:["local"],enterprise:["organization"],parity:["same-integrity"],equivalent:false},assumptions:["clock injected"],finish_conditions:["architecture authority"],non_goals:[{statement:"no execution",retained_by:["PG-04"]}],research_contract:{current:["current"],historical:["historical"],cross_disciplinary:["assurance"]},adverse_evidence_questions:["what fails"],falsifiers:["scope loss"],dependency_closures:[{id:"PG-03-T003",digest:D}],created_by:kind==="n1"?"owner":"alice",created_at:NOW,executable:false};
  const digest=goalDigest(body);
  const authority:AuthorityContextV1=kind==="n1"?{kind:"n1",goal_digest:digest,decision_id:"decision",decided_at:NOW,principal_id:"owner",authority_domain:"local-owner",verification_result:"PASS",custody_id:"custody"}:{kind:"enterprise",goal_digest:digest,decision_id:"decision",decided_at:NOW,principal_id:"alice",authority_domain:"organization",verification_result:"PASS",organization_id:"org",role_id:"maintainer",separation_policy_id:"sod",evidence_digest:E};
  const scope:GoalScopeAuthorityV1={known_scope_ids:["S1","S2"],required_scope_ids:["S1","S2"],required_track_obligations:{n1:["local"],enterprise:["organization"],parity:["same-integrity"]},dependency_closures:{"PG-03-T003":D}};
  const protocol:ResearchProtocolV1={schema_version:1,goal_digest:digest,predecessor_digest:D,questions:{current:"frontier?",historical:"failure?",cross_disciplinary:"transfer?"},inclusion_rules:["primary"],exclusion_rules:["unattributed"],freshness_policies:{mutable_current_months:3,versioned_standard:"IDENTITY",immutable_local:"IDENTITY"},expected_adverse_evidence:["scope loss"],falsifiers:["simpler mechanism"],required_consequence_classes:["goal_question","scope","architecture","requirement","threat","test_oracle"]};
  const row=(id:string,lane:"current"|"historical"|"cross-disciplinary",source_class:"mutable-current"|"versioned-standard"|"immutable-local",stance:"SUPPORTS"|"MIXED"|"ADVERSE")=>({row_id:id,lane,locator:`https://e.example/${id}`,query:`query-${id}`,candidate:`candidate-${id}`,observation:`observation-${id}`,observed_at:"2026-06-03T00:00:00Z",observed_identity:`identity-${id}`,source_class,disposition:"SELECTED" as const,disposition_reason:"selected",uncertainty:"bounded",evidence_stance:stance});
  const rows=[row("c","current","mutable-current","SUPPORTS"),row("h","historical","immutable-local","MIXED"),row("x","cross-disciplinary","versioned-standard","ADVERSE")];
  const classes=["goal_question","scope","architecture","requirement","threat","test_oracle"] as const;
  const record:GoalResearchRecordV1={schema_version:1,goal_digest:digest,predecessor_digest:D,protocol_digest:researchProtocolDigest(protocol),rows,adverse_evidence:["adverse"],falsifiers:["falsifier"],consequences:classes.map((c,i)=>({consequence_id:`k${i}`,class:c,statement:`${c} consequence`,mechanism:"bounded admission",source_row_ids:[rows[i%3]!.row_id]})),executable:false};
  const protocolDigest=researchProtocolDigest(protocol),researchDigest=digestValue(record);
  let state:GoalTransitionStateV1={schema_version:1,phase:"GOAL_PROPOSED",active_head_digest:digest,ancestor_digests:{goal:digest,protocol:protocolDigest,research:researchDigest},descendants:{protocol:{digest:H("1"),depends_on:["goal"],status:"ACTIVE"},research:{digest:H("2"),depends_on:["protocol"],status:"ACTIVE"},semantic_admission:{digest:H("3"),depends_on:["research"],status:"ACTIVE"},architecture:{digest:H("4"),depends_on:["semantic_admission"],status:"ACTIVE"},decomposition:{digest:H("5"),depends_on:["architecture"],status:"ACTIVE"},owner_approval:{digest:H("6"),depends_on:["decomposition"],status:"ACTIVE"},tickets:{digest:H("7"),depends_on:["owner_approval"],status:"ACTIVE"}},downstream_vets_consumed:0};
  const initial=clone(state);
  const transitions:GoalTransitionProposalV1[]=[];
  for(let i=1;i<GOAL_TRANSITION_PHASES.length;i++){
    const to=GOAL_TRANSITION_PHASES[i]!;const p:GoalTransitionProposalV1={schema_version:1,from_phase:state.phase,to_phase:to,expected_active_head_digest:state.active_head_digest,next_head_digest:H("0"),required_ancestor_digests:{...state.ancestor_digests},consequence_graph:graph(),semantic_admission:null,trusted_reviewer_ids:["reviewer"],expected_ticket_digest:H("a"),expected_policy_digest:H("b"),expected_evidence_digest:H("c"),authority_verdict:"PASS",supersedes:null,authority_context:kind==="n1"?{kind:"n1",principal_id:"owner",custody_id:"custody",organization_services:"ABSENT"}:{kind:"enterprise",organization_id:"org",actor_id:"alice",role_id:"maintainer",separation_policy_id:"sod",local_owner_substitution:false},downstream_vet:null};
    if(to==="RESEARCH_SEMANTIC_PASS")p.semantic_admission={schema_version:1,ticket_digest:H("a"),round:1,research_digest:p.required_ancestor_digests.research!,author_family:"OpenAI",reviewer_family:"Anthropic",reviewer_id:"reviewer",policy_digest:H("b"),evidence_digest:H("c"),reviewed_at:NOW,verdict:"PASS"};
    p.next_head_digest=to==="GOAL_ADMITTED"?digest:to==="RESEARCH_PROTOCOL_FROZEN"?protocolDigest:to==="RESEARCH_CANDIDATE"||to==="RESEARCH_STRUCTURAL_PASS"?researchDigest:to==="RESEARCH_SEMANTIC_PASS"?digestValue(p.semantic_admission):digestValue({goal_digest:digest,protocol_digest:protocolDigest,research_digest:researchDigest,semantic_digest:transitions.at(-1)!.next_head_digest,consequence_graph:p.consequence_graph});
    transitions.push(p);const advanced=evaluateGoalTransition(state,p);if(!advanced.advanced)throw new Error(advanced.code);state=advanced.state;
  }
  return {schema_version:1,goal_candidate:{body,goal_digest:digest},authority_context:authority,scope_authority:scope,research_protocol:protocol,research_record:record,observed_at:NOW,current_source_identities:Object.fromEntries(rows.map(r=>[r.locator,r.observed_identity])),transition_state:initial,transitions,executable:false};
}
function code(r:{state:{artifacts:Readonly<Record<string,unknown>>}}){return ((r as unknown as {goalLifecycle?:{code:string}}).goalLifecycle?.code)??(r.state.artifacts.goal_lifecycle as {code:string}).code}
async function run(req:GoalLifecycleRequestV1,id:string){return loop().runProject("structured goal",{runId:id,goalLifecycle:req})}

test("PG-03-T004-FC01 installed-shaped n=1 journey stops at architecture",async()=>{const called={value:0},r=await loop(undefined,called).runProject("n1",{runId:"fc01",goalLifecycle:fixture()});assert.equal(r.state.status,"completed");assert.equal(code(r),"ARCHITECTURE_AUTHORIZED");assert.equal(called.value,0);assert.deepEqual(Object.keys(r.state.artifacts),["goal_lifecycle"])});
test("PG-03-T004-FC02 enterprise journey retains organization ceremony",async()=>{const r=await run(fixture("enterprise"),"fc02");assert.equal(code(r),"ARCHITECTURE_AUTHORIZED");assert.equal(((r.state.artifacts.goal_lifecycle as {admitted_goal:{authority_context:{kind:string}}}).admitted_goal.authority_context.kind),"enterprise")});
test("PG-03-T004-FC03 generic consequences are refused",async()=>{const f=fixture();f.research_record=(clone(f.research_record) as GoalResearchRecordV1);(f.research_record as GoalResearchRecordV1).consequences=(f.research_record as GoalResearchRecordV1).consequences.filter(c=>c.class!=="architecture");assert.equal(code(await run(f,"fc03")),"CONSEQUENCE_ORPHAN")});
test("PG-03-T004-FC04 execution-bearing goal is refused after legal edge preflight",async()=>{const f=fixture();const c=f.goal_candidate as {body:GoalBodyV1;goal_digest:string};(c.body as unknown as {executable:boolean}).executable=true;c.goal_digest=goalDigest(c.body);(f.authority_context as AuthorityContextV1).goal_digest=c.goal_digest;assert.equal(code(await run(f,"fc04")),"GOAL_CANNOT_AUTHORIZE_EXECUTION")});
test("PG-03-T004-FC05 every checkpoint boundary resumes exactly once",async()=>{const store=new InMemoryProjectCheckpointStore(),f=fixture();let last=-1,r;for(let i=0;i<12;i++){r=await loop(store).runProject("restart",{runId:"fc05",goalLifecycle:f,stepBudget:1});assert.ok(r.state.revision>last);last=r.state.revision;if(r.state.status==="completed")break}assert.equal(r!.state.status,"completed");assert.equal(code(r!),"ARCHITECTURE_AUTHORIZED")});
test("PG-03-T004-FC06 display projection is not durable authority",async()=>{const f=fixture();f.goal_candidate={kind:"goal-display",goal_id:"x",title:"x",summary:"x",goal_digest:H("a")};assert.equal(code(await run(f,"fc06")),"TITLE_OR_SUMMARY_NOT_AUTHORITY")});
test("PG-03-T004-FC07 enterprise transition cannot resume through local-owner ceremony",async()=>{const f=fixture("enterprise"),local=fixture().transitions.map(p=>(p as GoalTransitionProposalV1).authority_context);f.transitions.forEach((p,i)=>(p as GoalTransitionProposalV1).authority_context=local[i]!);assert.equal(code(await run(f,"fc07")),"ENTERPRISE_AUTHORITY_REQUIRED")});
test("PG-03-T004-FC08 incomplete goal body is refused",async()=>{const f=fixture(),c=f.goal_candidate as {body:Record<string,unknown>};delete c.body.finish_conditions;assert.equal(code(await run(f,"fc08")),"INCOMPLETE_GOAL_BODY")});
test("PG-03-T004-FC09 renamed summary is not authority",async()=>{const f=fixture();f.goal_candidate={goal_id:"x",title:"renamed",summary:"summary",goal_digest:H("a")};assert.equal(code(await run(f,"fc09")),"TITLE_OR_SUMMARY_NOT_AUTHORITY")});
test("PG-03-T004-FC10 unknown scope is refused",async()=>{const f=fixture(),c=f.goal_candidate as {body:GoalBodyV1;goal_digest:string};c.body.scope_ids.push("UNKNOWN");c.goal_digest=goalDigest(c.body);(f.authority_context as AuthorityContextV1).goal_digest=c.goal_digest;assert.equal(code(await run(f,"fc10")),"UNKNOWN_SCOPE_ID")});
test("PG-03-T004-FC11 copied lane is refused",async()=>{const f=fixture(),r=f.research_record as GoalResearchRecordV1;Object.assign(r.rows[1]!,{locator:r.rows[0]!.locator,query:r.rows[0]!.query,observed_identity:r.rows[0]!.observed_identity});assert.equal(code(await run(f,"fc11")),"SOURCE_LEDGER_INCOMPLETE")});
test("PG-03-T004-FC12 duplicate citation identity is refused",async()=>{const f=fixture(),r=f.research_record as GoalResearchRecordV1;r.rows[1]!.row_id=r.rows[0]!.row_id;assert.equal(code(await run(f,"fc12")),"SOURCE_LEDGER_INCOMPLETE")});
test("PG-03-T004-FC13 grouped mutable source is refused",async()=>{const f=fixture(),r=f.research_record as GoalResearchRecordV1;r.rows[0]!.locator="https://a.example,https://b.example";assert.equal(code(await run(f,"fc13")),"SOURCE_LEDGER_INCOMPLETE")});
test("PG-03-T004-FC14 stale mutable source is refused",async()=>{const f=fixture();f.observed_at="2026-09-03T00:00:00.001Z";assert.equal(code(await run(f,"fc14")),"SOURCE_STALE")});
test("PG-03-T004-FC15 missing adverse evidence is refused",async()=>{const f=fixture(),r=f.research_record as GoalResearchRecordV1;r.adverse_evidence=[];assert.equal(code(await run(f,"fc15")),"ADVERSE_EVIDENCE_MISSING")});
test("PG-03-T004-FC16 broken reciprocal transition edge is refused",async()=>{const f=fixture(),p=f.transitions[0] as GoalTransitionProposalV1;p.consequence_graph.edges=p.consequence_graph.edges.filter(e=>e.from!=="mechanism");assert.equal(code(await run(f,"fc16")),"CONSEQUENCE_ORPHAN")});
test("PG-03-T004-FC17 candidate author cannot review itself",async()=>{const f=fixture(),p=f.transitions[4] as GoalTransitionProposalV1;p.semantic_admission!.reviewer_family=p.semantic_admission!.author_family;assert.equal(code(await run(f,"fc17")),"SEMANTIC_ADMISSION_INVALID")});
test("PG-03-T004-FC18 enterprise local-owner substitution is refused",async()=>{const f=fixture("enterprise"),local=clone(fixture().authority_context) as AuthorityContextV1;local.goal_digest=(f.goal_candidate as {goal_digest:string}).goal_digest;f.authority_context=local;assert.equal(code(await run(f,"fc18")),"ENTERPRISE_AUTHORITY_REQUIRED")});
test("PG-03-T004-FC19 n=1 transition refuses organization ceremony",async()=>{const f=fixture(),enterprise=fixture("enterprise").transitions.map(p=>(p as GoalTransitionProposalV1).authority_context);f.transitions.forEach((p,i)=>(p as GoalTransitionProposalV1).authority_context=enterprise[i]!);assert.equal(code(await run(f,"fc19")),"N1_ENTERPRISE_CEREMONY_FORBIDDEN")});
test("PG-03-T004-FC20 stale research transition is refused on resume",async()=>{const store=new InMemoryProjectCheckpointStore(),f=fixture(),p=f.transitions[3] as GoalTransitionProposalV1;p.expected_active_head_digest=H("f");await loop(store).runProject("stale",{runId:"fc20",goalLifecycle:f,stepBudget:5});const r=await loop(store).runProject("stale",{runId:"fc20",goalLifecycle:f});assert.equal(code(r),"STALE_DERIVATION")});
test("PG-03-T004-FC21 protocol skip is refused",async()=>{const f=fixture(),p=f.transitions[0] as GoalTransitionProposalV1;p.to_phase="RESEARCH_PROTOCOL_FROZEN";assert.equal(code(await run(f,"fc21")),"ILLEGAL_PHASE_EDGE")});
test("PG-03-T004-FC22 illegal edge wins over stale and execution claims",async()=>{const f=fixture(),p=f.transitions[0] as GoalTransitionProposalV1,c=f.goal_candidate as {body:GoalBodyV1;goal_digest:string};p.to_phase="ARCHITECTURE_AUTHORIZED";p.expected_active_head_digest=H("f");(c.body as unknown as {executable:boolean}).executable=true;c.goal_digest=goalDigest(c.body);(f.authority_context as AuthorityContextV1).goal_digest=c.goal_digest;assert.equal(code(await run(f,"fc22")),"ILLEGAL_PHASE_EDGE")});
test("PG-03-T004 hardening: malformed scope fails closed and rejected replay is idempotent",async()=>{const malformed=fixture();malformed.scope_authority=null;assert.equal(code(await run(malformed,"malformed-scope")),"MALFORMED_OR_UNKNOWN_FIELD");const store=new InMemoryProjectCheckpointStore(),f=fixture();(f.goal_candidate as {body:GoalBodyV1}).body.finish_conditions=[];const first=await loop(store).runProject("reject",{runId:"rejected-replay",goalLifecycle:f}),second=await loop(store).runProject("reject",{runId:"rejected-replay",goalLifecycle:f});assert.equal(second.state.revision,first.state.revision)});
test("PG-03-T004 hardening: a legacy run cannot be converted into structured authority",async()=>{const store=new InMemoryProjectCheckpointStore(),api=loop(store);await api.runProject("legacy",{runId:"legacy-mode",stepBudget:1});await assert.rejects(api.runProject("legacy",{runId:"legacy-mode",goalLifecycle:fixture()}),/legacy project mode/u)});
test("PG-03-T004 hardening: ancestry, derived heads, same-track identity, and chain origin are bound",async()=>{for(const [i,mutate] of [(f:MutableRequest)=>{(f.transition_state as GoalTransitionStateV1).ancestor_digests.goal=H("f")},(f:MutableRequest)=>{(f.transitions[2] as GoalTransitionProposalV1).next_head_digest=H("f")},(f:MutableRequest)=>{((f.transitions[0] as GoalTransitionProposalV1).authority_context as {principal_id:string}).principal_id="forged"},(f:MutableRequest)=>{(f.transition_state as GoalTransitionStateV1).phase="RESEARCH_SEMANTIC_PASS"}].entries()){const f=fixture();mutate(f);const result=await run(f,`binding-${i}`);assert.ok(["STALE_DERIVATION","TRACK_AUTHORITY_SUBSTITUTION","ILLEGAL_PHASE_EDGE"].includes(code(result)))}});
test("PG-03-T004 hardening: nested malformed requests return a denial and never throw",async()=>{for(const [i,mutate] of [(f:MutableRequest)=>{f.scope_authority={dependency_closures:{}}},(f:MutableRequest)=>{f.transitions=[f.transitions[0],null,f.transitions[2],f.transitions[3],f.transitions[4],f.transitions[5]]}].entries()){const f=fixture();mutate(f);assert.equal(code(await run(f,`malformed-${i}`)),"MALFORMED_OR_UNKNOWN_FIELD")}});

test("PG-05-T010 autonomy reconstructs after lifecycle projection deletion",async()=>{const store=new InMemoryProjectCheckpointStore(),api=loop(store),f=fixture();const partial=await api.runProject("event-resume",{runId:"t010-delete",goalLifecycle:f,stepBudget:3});store.save({...partial.state,revision:partial.state.revision+1,artifacts:{}},partial.state.revision);const resumed=await api.runProject("event-resume",{runId:"t010-delete",goalLifecycle:f});assert.equal(resumed.state.status,"completed");assert.equal(code(resumed),"ARCHITECTURE_AUTHORIZED")});
test("PG-05-T010 autonomy rejects forged projection without changing event authority",async()=>{const store=new InMemoryProjectCheckpointStore(),api=loop(store),f=fixture();const partial=await api.runProject("event-forge",{runId:"t010-forge",goalLifecycle:f,stepBudget:3}),artifact=clone(partial.state.artifacts.goal_lifecycle as GoalLifecycleArtifactV1) as unknown as {next_transition_index:number;code:string};artifact.next_transition_index=6;artifact.code="ARCHITECTURE_AUTHORIZED";store.save({...partial.state,revision:partial.state.revision+1,artifacts:{goal_lifecycle:artifact as unknown as GoalLifecycleArtifactV1}},partial.state.revision);const refused=await api.runProject("event-forge",{runId:"t010-forge",goalLifecycle:f});assert.equal(code(refused),"LEGACY_GOAL_MUTATION_REJECTED");assert.equal((refused as unknown as {goalLifecycle:{artifact:GoalLifecycleArtifactV1}}).goalLifecycle.artifact.next_transition_index,1)});
test("PG-05-T013 installed goal lifecycle publishes and rebuilds only an event-derived status view",async()=>{const checkpoints=new InMemoryProjectCheckpointStore(),firstViews=new InMemoryEngineeringStatusProjectionStoreV1(),f=fixture();await loop(checkpoints,undefined,firstViews).runProject("projected",{runId:"t013-installed",goalLifecycle:f});const first=firstViews.load("t013-installed");assert.equal(first?.statuses.goal?.phase,"ARCHITECTURE_AUTHORIZED");assert.equal(first?.authoritative,false);const rebuiltViews=new InMemoryEngineeringStatusProjectionStoreV1();await loop(checkpoints,undefined,rebuiltViews).runProject("projected",{runId:"t013-installed",goalLifecycle:f});assert.deepEqual(rebuiltViews.load("t013-installed"),first);});
test("PG-05-T013 unavailable projection cache cannot block an authoritative lifecycle",async()=>{const unavailable:EngineeringStatusProjectionStoreV1={load(){throw new Error("cache unavailable")},compareAndSave(){throw new Error("cache unavailable")}};const result=await loop(new InMemoryProjectCheckpointStore(),undefined,unavailable).runProject("cache-independent",{runId:"t013-cache-failure",goalLifecycle:fixture()});assert.equal(result.state.status,"completed");assert.equal(code(result),"ARCHITECTURE_AUTHORIZED");});
