import { test } from "node:test";
import assert from "node:assert/strict";
import { generateKeyPairSync, sign } from "node:crypto";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { eirDigest, encodeCanonical } from "../src/eir/canonical.js";
import { AuthoritativeAppendV1 } from "../src/spine/authoritative_append_v1.js";
import { CommittedHeadV1, type CommittedHeadV1WitnessAck, type CommittedHeadV1WitnessPort } from "../src/spine/committed_head_v1.js";
import { type EventAdmissionV1TrustedContext } from "../src/spine/event_admission_v1.js";
import { EventEnvelopeV1CodecIdentity, EventEnvelopeV1Schema, type EventEnvelopeV1Value } from "../src/spine/event_envelope_v1.js";
import { ReducerRegistryV1 } from "../src/spine/reducer_registry_v1.js";
import { validateReplayProjectionV1, type ReplayProjectionV1Authority, type ReplayProjectionV1Value } from "../src/spine/replay_projection_v1.js";
import { EventVersionRegistryV1 } from "../src/spine/version_registry_v1.js";

const keys=generateKeyPairSync("ed25519"),publicKey=keys.publicKey.export({type:"spki",format:"pem"}).toString();
class Witness implements CommittedHeadV1WitnessPort{
  current:CommittedHeadV1WitnessAck|null=null;
  async latest(){return this.current}
  async compareAndPersist(expected:string|null,bytes:Uint8Array):Promise<CommittedHeadV1WitnessAck>{const current=this.current?.ok===true?this.current.checkpoint_digest:null;if(current!==expected)return{ok:false,code:"WITNESS_CONFLICT"};const ack={ok:true,durable:true,checkpoint_bytes:bytes.slice(),checkpoint_digest:eirDigest("keep.spine.committed-head-checkpoint-bytes.v1",bytes),signature:new Uint8Array(sign(null,bytes,keys.privateKey))} as const;this.current=ack;return ack}
}
const context=(kind:"n1"|"enterprise"):EventAdmissionV1TrustedContext=>kind==="n1"
  ?{kind:"n1",track:"n1",history_id:"projection-local",actor_id:"owner",authority_domain:"local",custody_id:"disk",committed_lineage:[],witnessed_head:null}
  :{kind:"enterprise",track:"enterprise",history_id:"projection-enterprise",actor_id:"agent",authority_domain:"org/tenant",custody_id:"hsm",organization_id:"org",tenant_id:"tenant",actor_role_id:"release",isolation_id:"iso",committed_lineage:[],witnessed_head:null};
const proposal=(c:EventAdmissionV1TrustedContext):EventEnvelopeV1Value=>({schema:EventEnvelopeV1Schema,schema_version:1n,codec:EventEnvelopeV1CodecIdentity,codec_version:1n,history_id:c.history_id,sequence:0n,predecessor_event_id:null,predecessor_head_id:null,event_type:"goal.admitted",actor_id:c.actor_id,authority_domain:c.authority_domain,track:c.track,payload:{value:"history"},effect_correlation:null});
async function replay(kind:"n1"|"enterprise"):Promise<ReplayProjectionV1Authority>{
  const c=context(kind),p=proposal(c),root=mkdtempSync(join(tmpdir(),"keep-t007-")),witness=new Witness();
  const committed_head=await new CommittedHeadV1({append:new AuthoritativeAppendV1({storage_root:root,durability_profile:{kind:"verified-local-posix-v1",max_record_bytes:1_048_576n}}),history_storage_domain:"history-disk",witness_storage_domain:"witness-disk",witness,witness_public_key:publicKey}).commit(p,c);assert.equal(committed_head.ok,true);if(!committed_head.ok)throw new Error("head fixture failed");
  const reduction=new ReducerRegistryV1([{event_type:"goal.admitted",event_schema_version:1n,reducer_id:"goal",reducer_version:1n,transition:"replace-state-with-event-payload",capabilities:[]}]).reduce(encodeCanonical({value:"before"}),p,c);assert.equal(reduction.ok,true);if(!reduction.ok)throw new Error("reducer fixture failed");
  const versions=new EventVersionRegistryV1([{event_type:"goal.admitted",from_version:1n,to_version:2n,upcaster_id:"goal-v1-v2",upcaster_version:1n,operation:"retain-payload"}]),set=versions.interpreterSet("goal.admitted",1n,2n);assert.equal(set.ok,true);if(!set.ok)throw new Error("version fixture failed");const version=versions.upcast(p,c,2n,set.interpreter_set_digest);assert.equal(version.ok,true);if(!version.ok)throw new Error("upcast fixture failed");
  return{committed_head,reduction,version,codec:EventEnvelopeV1CodecIdentity,codec_version:1n};
}
const projection=(r:ReplayProjectionV1Authority):ReplayProjectionV1Value=>({schema:"keep.spine.replay-projection",schema_version:1n,history_id:r.committed_head.receipt.history_id,next_head_id:r.committed_head.receipt.next_head_id,event_id:r.committed_head.receipt.event_id,sequence:r.committed_head.receipt.sequence,event_count:r.committed_head.receipt.sequence+1n,authority:r.committed_head.receipt.authority,codec:r.codec,codec_version:r.codec_version,reducer_identity:r.reduction.reducer_identity,interpreter_set_digest:r.version.interpreter_set_digest,state_bytes:r.reduction.state_bytes.slice(),state_digest:r.reduction.state_digest,authoritative:false,acceleration_only:true});

test("PG-05-T007-FC01 exact n1 projection accelerates but history supplies state",async()=>{const r=await replay("n1"),p=projection(r),out=validateReplayProjectionV1(r,p);assert.equal(out.ok,true);if(out.ok){assert.equal(out.projection_accepted,true);assert.equal(out.authoritative_source,"history-replay");assert.equal(out.projection_authoritative,false);assert.deepEqual(out.state_bytes,r.reduction.state_bytes);assert.notEqual(out.state_bytes,p.state_bytes);p.state_bytes[0]=(p.state_bytes[0]??0)^0xff;assert.deepEqual(out.state_bytes,r.reduction.state_bytes);assert.equal(out.state_digest,r.reduction.state_digest)}});
test("PG-05-T007-FC02 exact enterprise projection retains direct tenant authority",async()=>{const r=await replay("enterprise"),out=validateReplayProjectionV1(r,projection(r));assert.equal(out.ok,true);if(out.ok){assert.equal(out.authority.kind,"enterprise");if(out.authority.kind==="enterprise")assert.deepEqual([out.authority.organization_id,out.authority.tenant_id,out.authority.actor_role_id,out.authority.isolation_id],["org","tenant","release","iso"])}});
test("PG-05-T007-FC03 projection without established history returns HISTORY_REQUIRED",async()=>{const p=projection(await replay("n1"));assert.deepEqual(validateReplayProjectionV1(null,p),{ok:false,code:"HISTORY_REQUIRED"});const broken=await replay("n1");(broken as {codec_version:bigint}).codec_version=2n;assert.deepEqual(validateReplayProjectionV1(broken,p),{ok:false,code:"HISTORY_REQUIRED"})});
test("PG-05-T007-FC04 any history coordinate or state mismatch discards projection",async()=>{const r=await replay("n1"),p=projection(r);for(const changed of [{...p,history_id:"other"},{...p,next_head_id:"f".repeat(64)},{...p,event_id:"e".repeat(64)},{...p,sequence:1n},{...p,event_count:2n},{...p,state_digest:"d".repeat(64)}]){const out=validateReplayProjectionV1(r,changed);assert.equal(out.ok,false);if(!out.ok&&out.code!=="HISTORY_REQUIRED"){assert.equal(out.code,"PROJECTION_HISTORY_MISMATCH");assert.equal(out.projection_discarded,true);assert.deepEqual(out.state_bytes,r.reduction.state_bytes)}}});
test("PG-05-T007-FC05 codec reducer or upcaster drift cannot reuse projection",async()=>{const r=await replay("n1"),p=projection(r);for(const changed of [{...p,codec:"other"},{...p,codec_version:2n},{...p,reducer_identity:"a".repeat(64)},{...p,interpreter_set_digest:"b".repeat(64)}]){const out=validateReplayProjectionV1(r,changed);assert.equal(out.ok,false);if(!out.ok)assert.equal(out.code,"PROJECTION_INTERPRETER_MISMATCH")}});
test("PG-05-T007-FC06 track or enterprise tenant substitution fails before reuse",async()=>{const r=await replay("enterprise"),p=projection(r);assert.equal(p.authority.kind,"enterprise");if(p.authority.kind!=="enterprise")return;for(const authority of [{kind:"n1",track:"n1",actor_id:"owner",authority_domain:"local",custody_id:"disk"} as const,{...p.authority,tenant_id:"other"},{...p.authority,organization_id:"other"}]){const out=validateReplayProjectionV1(r,{...p,authority});assert.equal(out.ok,false);if(!out.ok)assert.equal(out.code,"TRACK_AUTHORITY_SUBSTITUTION")}});
test("PG-05-T007-FC07 forged newer checkpoint is inert and replay state wins",async()=>{const r=await replay("n1"),p=projection(r),forged=encodeCanonical({value:"forged"}),out=validateReplayProjectionV1(r,{...p,next_head_id:"f".repeat(64),sequence:p.sequence+1n,event_count:p.event_count+1n,state_bytes:forged,state_digest:eirDigest("keep.spine.reducer-state-bytes.v1",forged)});assert.equal(out.ok,false);if(!out.ok&&out.code!=="HISTORY_REQUIRED"){assert.equal(out.code,"PROJECTION_HISTORY_MISMATCH");assert.deepEqual(out.state_bytes,r.reduction.state_bytes);assert.equal(out.state_digest,r.reduction.state_digest)}});
