import { test } from "node:test";
import assert from "node:assert/strict";

import { decodeCanonical, encodeCanonical, type CanonicalValue } from "../src/eir/canonical.js";
import { type EventAdmissionV1TrustedContext } from "../src/spine/event_admission_v1.js";
import { EventEnvelopeV1CodecIdentity, EventEnvelopeV1Schema, type EventEnvelopeV1Value } from "../src/spine/event_envelope_v1.js";
import { EventVersionRegistryV1, type EventVersionRegistryV1Definition } from "../src/spine/version_registry_v1.js";

const n1=():EventAdmissionV1TrustedContext=>({kind:"n1",track:"n1",history_id:"version-history",actor_id:"owner",authority_domain:"local",custody_id:"disk",committed_lineage:[],witnessed_head:null});
const enterprise=():EventAdmissionV1TrustedContext=>({kind:"enterprise",track:"enterprise",history_id:"version-history",actor_id:"agent",authority_domain:"org/tenant",custody_id:"hsm",organization_id:"org",tenant_id:"tenant",actor_role_id:"role",isolation_id:"iso",committed_lineage:[],witnessed_head:null});
const proposal=(c:EventAdmissionV1TrustedContext,payload:CanonicalValue={name:"Ada"}):EventEnvelopeV1Value=>({schema:EventEnvelopeV1Schema,schema_version:1n,codec:EventEnvelopeV1CodecIdentity,codec_version:1n,history_id:c.history_id,sequence:0n,predecessor_event_id:null,predecessor_head_id:null,event_type:"goal.admitted",actor_id:c.actor_id,authority_domain:c.authority_domain,track:c.track,payload,effect_correlation:null});
const definitions=():EventVersionRegistryV1Definition[]=>[
  {event_type:"goal.admitted",from_version:1n,to_version:2n,upcaster_id:"goal-v1-v2",upcaster_version:1n,operation:"merge-record-fields",fields:{enabled:true}},
  {event_type:"goal.admitted",from_version:2n,to_version:3n,upcaster_id:"goal-v2-v3",upcaster_version:1n,operation:"merge-record-fields",fields:{level:3n}},
];
const execute=(registry:EventVersionRegistryV1,c=n1(),p:unknown=proposal(c),target=3n,expected?:string)=>{const set=registry.interpreterSet("goal.admitted",1n,target);return registry.upcast(p,c,target,expected??(set.ok?set.interpreter_set_digest:"0".repeat(64)));};

test("PG-05-T006-FC01 complete adjacent v1-to-v3 chain yields golden value and ordered identities",()=>{const registry=new EventVersionRegistryV1(definitions()),set=registry.interpreterSet("goal.admitted",1n,3n);assert.equal(set.ok,true);const result=execute(registry);assert.equal(result.ok,true);if(set.ok&&result.ok){assert.deepEqual(result.adapter_identities,["b6c61aa9c025fc730e9e88618f053862776ba0a785baa4c12475150d96343d2c","748467f1bbe962b8cfff627154a403c34d136ccc724dd2324fdd4a9bac8b5ce1"]);assert.equal(result.interpreter_set_digest,"f2293f3936a4b9af147ef4ddc2322411c5da9069f778df605a8d533d97f665cd");assert.deepEqual(result.adapter_identities,set.adapter_identities);assert.equal(result.interpreter_set_digest,set.interpreter_set_digest);assert.equal(result.source_version,1n);assert.equal(result.target_version,3n);const current=decodeCanonical(result.current_event_bytes) as Record<string,CanonicalValue>;assert.equal(current.schema_version,3n);assert.deepEqual(current.payload,Object.assign(Object.create(null),{name:"Ada",enabled:true,level:3n}));}});
test("PG-05-T006-FC02 both tracks share core semantics and retain distinct direct authority",()=>{const registry=new EventVersionRegistryV1(definitions()),local=execute(registry,n1(),proposal(n1())),org=execute(registry,enterprise(),proposal(enterprise()));assert.equal(local.ok,true);assert.equal(org.ok,true);if(local.ok&&org.ok){const lp=decodeCanonical(local.current_event_bytes) as Record<string,CanonicalValue>,op=decodeCanonical(org.current_event_bytes) as Record<string,CanonicalValue>;assert.deepEqual(lp.payload,op.payload);assert.equal(local.authority.kind,"n1");assert.equal(org.authority.kind,"enterprise");if(org.authority.kind==="enterprise")assert.equal(org.authority.tenant_id,"tenant");}});
test("PG-05-T006-FC03 unsupported envelope source or target refuses as unknown without fallback",()=>{const registry=new EventVersionRegistryV1(definitions()),c=n1(),bad={...proposal(c),schema_version:9n};assert.deepEqual(execute(registry,c,bad),{ok:false,code:"UNKNOWN_EVENT_VERSION"});assert.deepEqual(execute(registry,c,proposal(c),0n),{ok:false,code:"UNKNOWN_EVENT_VERSION"});});
test("PG-05-T006-FC04 direct version skip is never accepted",()=>{const direct={event_type:"goal.admitted",from_version:1n,to_version:3n,upcaster_id:"skip",upcaster_version:1n,operation:"retain-payload"};const registry=new EventVersionRegistryV1([direct]);assert.deepEqual(registry.interpreterSet("goal.admitted",1n,3n),{ok:false,code:"UPCASTER_CHAIN_INCOMPLETE"});assert.deepEqual(execute(registry),{ok:false,code:"UPCASTER_CHAIN_INCOMPLETE"});});
test("PG-05-T006-FC05 missing duplicate or order-inconsistent links fail closed",()=>{for(const defs of [[definitions()[0]!],[...definitions(),definitions()[0]!],[definitions()[1]!,definitions()[0]!]]){const registry=new EventVersionRegistryV1(defs);assert.deepEqual(registry.interpreterSet("goal.admitted",1n,3n),{ok:false,code:"UPCASTER_CHAIN_INCOMPLETE"});assert.deepEqual(execute(registry),{ok:false,code:"UPCASTER_CHAIN_INCOMPLETE"});}});
test("PG-05-T006-FC06 definition drift changes identity and stale expected set refuses",()=>{const original=new EventVersionRegistryV1(definitions()),changedDefs=definitions();changedDefs[1]={event_type:"goal.admitted",from_version:2n,to_version:3n,upcaster_id:"goal-v2-v3",upcaster_version:1n,operation:"merge-record-fields",fields:{level:4n}};const changed=new EventVersionRegistryV1(changedDefs),a=original.interpreterSet("goal.admitted",1n,3n),b=changed.interpreterSet("goal.admitted",1n,3n);assert.equal(a.ok,true);assert.equal(b.ok,true);if(a.ok&&b.ok){assert.notEqual(a.interpreter_set_digest,b.interpreter_set_digest);assert.deepEqual(execute(changed,n1(),proposal(n1()),3n,a.interpreter_set_digest),{ok:false,code:"UPCASTER_SET_MISMATCH"});}});
test("PG-05-T006-FC07 original bytes and inputs never change and executable or rewrite definitions refuse",()=>{const c=n1(),p=proposal(c),before=encodeCanonical(p as unknown as CanonicalValue),registry=new EventVersionRegistryV1(definitions()),result=execute(registry,c,p);assert.equal(result.ok,true);if(result.ok)assert.deepEqual(result.original_event_bytes,before);assert.deepEqual(encodeCanonical(p as unknown as CanonicalValue),before);for(const invalid of [{...definitions()[0]!,rewrite_stored_bytes:true},{...definitions()[0]!,callback:()=>1}])assert.deepEqual(new EventVersionRegistryV1([invalid]).interpreterSet("goal.admitted",1n,2n),{ok:false,code:"VERSION_REGISTRY_DEFINITION_INVALID"});let called=0;const accessor=Object.defineProperty({...definitions()[0]!},"upcaster_id",{enumerable:true,get(){called++;return "bad"}});assert.deepEqual(new EventVersionRegistryV1([accessor]).interpreterSet("goal.admitted",1n,2n),{ok:false,code:"VERSION_REGISTRY_DEFINITION_INVALID"});assert.equal(called,0);assert.deepEqual(new EventVersionRegistryV1([new Proxy(definitions()[0]!,{})]).interpreterSet("goal.admitted",1n,2n),{ok:false,code:"VERSION_REGISTRY_DEFINITION_INVALID"});});
