/**
 * Bounded counterexample-guided checking of candidate skills. Acceptance requires a nonempty generated
 * batch and success on all retained cases, including cases encountered before refinement. The supplied
 * generator defines the sampled task coverage; the supplied oracle must execute the candidate and check
 * its actual result in isolated state. This class cannot establish that those trusted ports do so.
 *
 * Optional typed-program examples and envelope checks are separate prerequisites. A validated verdict
 * reports sampled execution success, not universal safety, immunity to manipulation, or improvement over
 * a baseline. Comparative usefulness is evaluated separately by SkillEvaluator.
 */

import type { DistilledSkill } from "./skill_distiller.js";
import { verifySkillProgram, type SkillPrograms } from "./skill_program.js";

/** Round budget (matches the MetaHarness CEGIS caps, K2). */
export const CEGIS_TARGET_ROUNDS = 3;
export const CEGIS_CEILING_ROUNDS = 5;

/** A concrete case the skill is executed against (skill-relevant; generated by PBT/fuzzing at the floor). */
export interface SkillCase {
  readonly id: string;
  /** The input the case exercises (e.g. a task variant of the skill's relevance shape). */
  readonly input: string;
}

/**
 * Trusted execution/checking port. Implementations must derive outcomes from candidate behavior and
 * independently specified task checks, and isolate state across invocations. A model's approval is not
 * execution evidence. SkillValidator uses runWithSkill; SkillEvaluator also consumes runBaseline.
 */
export interface ExecutionOracle {
  /** Run WITH the skill applied. Returns whether the produced result passed its tests. */
  runWithSkill(skill: DistilledSkill, testCase: SkillCase): boolean;
  /** Run WITHOUT the skill (baseline). Passing here + failing with-skill = the skill REGRESSED this case. */
  runBaseline(testCase: SkillCase): boolean;
}

/** Generates skill-relevant counterexample candidates (PBT/fuzzing at the floor; richer generators later). */
export interface CounterexampleGenerator {
  /** Produce a batch of candidate cases to try to refute the skill on. */
  generate(skill: DistilledSkill, round: number): readonly SkillCase[];
}

/** Refines a skill given a concrete refuting counterexample (returns null to abandon). */
export type SkillRefiner = (skill: DistilledSkill, counterexample: SkillCase, round: number) => DistilledSkill | null;

/** A safety check over the skill's envelope (the reference-monitor clause set). */
export interface EnvelopeSafetyCheck {
  /** Returns a violation reason if the skill's envelope is unsafe, else null. */
  check(skill: DistilledSkill): string | null;
}

export type ValidationVerdict = "validated" | "abandoned-unrefinable" | "abandoned-budget" | "rejected-unsafe" | "rejected-no-evidence";

/** Actual oracle invocations in this validation, distinct from optional typed-program examples. */
export interface SkillCaseExecution {
  readonly round: number;
  readonly testCase: SkillCase;
  readonly passed: boolean;
}

export interface ValidationResult {
  readonly verdict: ValidationVerdict;
  readonly skill: DistilledSkill; // the final (possibly refined) skill
  readonly rounds: number;
  /** Every counterexample that refuted a candidate, in order (the audit trail). */
  readonly counterexamples: readonly { readonly round: number; readonly caseId: string }[];
  readonly executedCases: readonly SkillCaseExecution[];
  readonly reason: string;
}

export interface SkillValidatorConfig {
  readonly oracle: ExecutionOracle;
  readonly generator: CounterexampleGenerator;
  readonly refiner: SkillRefiner;
  /** Optional envelope safety check (the reference-monitor clauses). */
  readonly safety?: EnvelopeSafetyCheck;
  /** Host implementations for optional typed skill contracts. Missing implementations fail closed. */
  readonly programs?: SkillPrograms;
  readonly maxRounds?: number;
}

export class SkillValidator {
  private readonly oracle: ExecutionOracle;
  private readonly generator: CounterexampleGenerator;
  private readonly refiner: SkillRefiner;
  private readonly safety: EnvelopeSafetyCheck | undefined;
  private readonly ceiling: number;
  private readonly programs: SkillPrograms;

  constructor(config: SkillValidatorConfig) {
    this.oracle = config.oracle;
    this.generator = config.generator;
    this.refiner = config.refiner;
    this.safety = config.safety;
    this.programs = config.programs ?? {};
    this.ceiling = Math.min(Math.max(1, config.maxRounds ?? CEGIS_TARGET_ROUNDS), CEGIS_CEILING_ROUNDS);
  }

  /**
   * All cases sampled during this invocation remain required. There is no runtime-enforced applicability
   * exclusion in this contract: changing prose/preconditions does not drop earlier obligations. A genuinely
   * narrower deployment needs a separately enforced consumer boundary and its own scoped evaluation.
   */
  validate(candidate: DistilledSkill): ValidationResult {
    let skill = candidate;
    const counterexamples: { round: number; caseId: string }[] = [];
    const executedCases: SkillCaseExecution[] = [];
    const retained = new Map<string, SkillCase>();

    for (let round = 1; round <= this.ceiling; round++) {
      const program = verifySkillProgram(skill, this.programs);
      if (!program.ok) {
        return { verdict: "rejected-unsafe", skill, rounds: round, counterexamples, executedCases, reason: `typed program verification failed: ${program.detail}` };
      }
      // Envelope safety FIRST (a structurally-unsafe skill is rejected regardless of execution).
      const unsafe = this.safety?.check(skill);
      if (unsafe) {
        return { verdict: "rejected-unsafe", skill, rounds: round, counterexamples, executedCases, reason: `envelope unsafe: ${unsafe}` };
      }

      const cases = this.generator.generate(skill, round);
      if (cases.length === 0) {
        return { verdict: "rejected-no-evidence", skill, rounds: round, counterexamples, executedCases, reason: `no generated execution cases in round ${round}; typed examples do not replace task validation` };
      }
      for (const c of cases) {
        // Copy string values before calling either mutable external port. IDs alone cannot identify inputs.
        const key = JSON.stringify([c.id, c.input]);
        if (!retained.has(key)) retained.set(key, Object.freeze({ id: c.id, input: c.input }));
      }
      const refuter = this.findCounterexample(skill, [...retained.values()], round, executedCases);

      if (!refuter) {
        return { verdict: "validated", skill, rounds: round, counterexamples, executedCases, reason: `passed all ${retained.size} retained execution cases in round ${round}; sampled success, not a proof or comparative improvement` };
      }

      counterexamples.push({ round, caseId: refuter.id });
      if (round === this.ceiling) break; // Return the tested candidate, not an untested final refinement.
      const refined = this.refiner(skill, refuter, round);
      if (!refined) {
        return { verdict: "abandoned-unrefinable", skill, rounds: round, counterexamples, executedCases, reason: `refiner could not address counterexample ${refuter.id} — abandoned (not shipped)` };
      }
      skill = refined;
    }

    return { verdict: "abandoned-budget", skill, rounds: this.ceiling, counterexamples, executedCases, reason: `execution cases still fail after ${this.ceiling} rounds — abandoned (not shipped)` };
  }

  /**
   * Stop at the first failing case. Baseline outcomes are not measured here; failure alone refutes this
   * sampled validation. Successful final rounds execute the entire retained set against the final skill.
   */
  private findCounterexample(skill: DistilledSkill, cases: readonly SkillCase[], round: number, executedCases: SkillCaseExecution[]): SkillCase | null {
    for (const c of cases) {
      const withSkill = this.oracle.runWithSkill(skill, c) === true;
      executedCases.push(Object.freeze({ round, testCase: c, passed: withSkill }));
      if (!withSkill) {
        return c;
      }
    }
    return null;
  }
}
