/**
 * SkillValidator (Increment 18.5, Phase S) — the CEGIS gate. This is the centerpiece of Keep's moat and the
 * reason 18.4 only produces CANDIDATES: no distilled skill goes live until it clears counterexample-guided,
 * EXECUTION-ADJUDICATED validation. The verdict comes from running the skill against concrete cases, never
 * from a model asserting the skill is good — which is what makes it immune to debate-hacking / sycophancy.
 *
 * SOTA basis (2026-08-05):
 *  - CEGIS is a learner↔verifier loop (arXiv 2509.04288): propose → VERIFY against the spec → on violation,
 *    PRODUCE A COUNTEREXAMPLE → refine with it → repeat until the property holds or the budget is spent.
 *  - The verdict must be grounded in CONCRETE TRACE EVIDENCE — tool call / file state / command output — not
 *    a compliance CLAIM (Skill Coverage arXiv 2606.20659). → the execution oracle (Keep's verifyPatch on the
 *    skill's produced patch) is the adjudicator; a model is never the judge.
 *  - The verification GATE is a distinct, load-bearing contributor (SkillGen 2605.10999): a skill is not
 *    trusted until it clears the gate.
 *  - Anti-pattern this defends against: 49,943 unvalidated OpenClaw registry skills with measurable
 *    instruction-manipulation deviations (Behavioral Integrity Verification 2026) — Keep validates behavior
 *    BEFORE deployment.
 *  - Round budget cap 3 / ceiling 5, early-stop on no-new-counterexample (KEEP_KNOBS_RESOLVED K2 — the
 *    diminishing-returns + reward-hacking plateau).
 *
 * Zero runtime deps. The execution oracle + counterexample generator are ports (swappable; PBT/fuzzing at the
 * floor, richer generators at the rich tier).
 */

import type { DistilledSkill } from "./skill_distiller.js";
import { verifySkillProgram, type SkillPrograms } from "./skill_program.js";

/** Round budget (matches the MetaHarness CEGIS caps, K2). */
export const CEGIS_TARGET_ROUNDS = 3;
export const CEGIS_CEILING_ROUNDS = 5;

/** A concrete case the skill is executed against (skill-relevant; generated by PBT/fuzzing at the floor). */
export interface SkillCase {
  readonly id: string;
  /** The input the case exercises (e.g. a task variant of the skill's relevance shape). */
  readonly input: string;
}

/**
 * The EXECUTION ORACLE — the adjudicator. Runs a skill against a case and returns a CONCRETE, execution-
 * grounded outcome (did applying the skill produce a passing result, and did it regress vs not using it?).
 * In Keep this is backed by verifyPatch (tests on the produced patch). NEVER a model verdict.
 */
export interface ExecutionOracle {
  /** Run WITH the skill applied. Returns whether the produced result passed its tests. */
  runWithSkill(skill: DistilledSkill, testCase: SkillCase): boolean;
  /** Run WITHOUT the skill (baseline). Passing here + failing with-skill = the skill REGRESSED this case. */
  runBaseline(testCase: SkillCase): boolean;
}

/** Generates skill-relevant counterexample candidates (PBT/fuzzing at the floor; richer generators later). */
export interface CounterexampleGenerator {
  /** Produce a batch of candidate cases to try to refute the skill on. */
  generate(skill: DistilledSkill, round: number): readonly SkillCase[];
}

/** Refines a skill given a concrete refuting counterexample (returns null to abandon). */
export type SkillRefiner = (skill: DistilledSkill, counterexample: SkillCase, round: number) => DistilledSkill | null;

/** A safety check over the skill's envelope (the reference-monitor clause set). */
export interface EnvelopeSafetyCheck {
  /** Returns a violation reason if the skill's envelope is unsafe, else null. */
  check(skill: DistilledSkill): string | null;
}

export type ValidationVerdict = "validated" | "abandoned-unrefinable" | "abandoned-budget" | "rejected-unsafe";

export interface ValidationResult {
  readonly verdict: ValidationVerdict;
  readonly skill: DistilledSkill; // the final (possibly refined) skill
  readonly rounds: number;
  /** Every counterexample that refuted a candidate, in order (the audit trail). */
  readonly counterexamples: readonly { readonly round: number; readonly caseId: string }[];
  readonly reason: string;
}

export interface SkillValidatorConfig {
  readonly oracle: ExecutionOracle;
  readonly generator: CounterexampleGenerator;
  readonly refiner: SkillRefiner;
  /** Optional envelope safety check (the reference-monitor clauses). */
  readonly safety?: EnvelopeSafetyCheck;
  /** Host implementations for optional typed skill contracts. Missing implementations fail closed. */
  readonly programs?: SkillPrograms;
  readonly maxRounds?: number;
}

export class SkillValidator {
  private readonly oracle: ExecutionOracle;
  private readonly generator: CounterexampleGenerator;
  private readonly refiner: SkillRefiner;
  private readonly safety: EnvelopeSafetyCheck | undefined;
  private readonly ceiling: number;
  private readonly programs: SkillPrograms;

  constructor(config: SkillValidatorConfig) {
    this.oracle = config.oracle;
    this.generator = config.generator;
    this.refiner = config.refiner;
    this.safety = config.safety;
    this.programs = config.programs ?? {};
    this.ceiling = Math.min(Math.max(1, config.maxRounds ?? CEGIS_TARGET_ROUNDS), CEGIS_CEILING_ROUNDS);
  }

  /**
   * Validate a candidate skill via the CEGIS loop. Returns "validated" only if a round finds NO refuting
   * counterexample (fix-point) AND the envelope is safe. Otherwise the skill is ABANDONED (never shipped).
   */
  validate(candidate: DistilledSkill): ValidationResult {
    let skill = candidate;
    const counterexamples: { round: number; caseId: string }[] = [];

    for (let round = 1; round <= this.ceiling; round++) {
      const program = verifySkillProgram(skill, this.programs);
      if (!program.ok) {
        return { verdict: "rejected-unsafe", skill, rounds: round, counterexamples, reason: `typed program verification failed: ${program.detail}` };
      }
      // Envelope safety FIRST (a structurally-unsafe skill is rejected regardless of execution).
      const unsafe = this.safety?.check(skill);
      if (unsafe) {
        return { verdict: "rejected-unsafe", skill, rounds: round, counterexamples, reason: `envelope unsafe: ${unsafe}` };
      }

      // VERIFY by EXECUTION: find a concrete case the skill REGRESSES (passes baseline, fails with the skill),
      // or simply fails to solve. That case is the refuting counterexample.
      const cases = this.generator.generate(skill, round);
      const refuter = this.findCounterexample(skill, cases);

      if (!refuter) {
        // Fix-point: no counterexample this round → the skill holds under execution. VALIDATED.
        return { verdict: "validated", skill, rounds: round, counterexamples, reason: `no refuting counterexample after ${round} round(s) — execution-adjudicated fix-point` };
      }

      counterexamples.push({ round, caseId: refuter.id });
      const refined = this.refiner(skill, refuter, round);
      if (!refined) {
        return { verdict: "abandoned-unrefinable", skill, rounds: round, counterexamples, reason: `refiner could not address counterexample ${refuter.id} — abandoned (not shipped)` };
      }
      skill = refined;
    }

    // Budget exhausted without a fix-point → abandon. A non-converging skill is NEVER shipped.
    return { verdict: "abandoned-budget", skill, rounds: this.ceiling, counterexamples, reason: `no fix-point within ${this.ceiling} rounds — abandoned (not shipped)` };
  }

  /**
   * Find a concrete case that refutes the skill: it REGRESSED the case (baseline passed but with-skill failed)
   * — the strongest refutation — or failed to solve a case at all. Execution-adjudicated; no model verdict.
   */
  private findCounterexample(skill: DistilledSkill, cases: readonly SkillCase[]): SkillCase | null {
    for (const c of cases) {
      const withSkill = this.oracle.runWithSkill(skill, c);
      if (!withSkill) {
        // A failure. Is it a REGRESSION (baseline would have passed)? Either way it's a valid counterexample:
        // a skill that fails a relevant case has not earned trust. Regression is the strongest form.
        return c;
      }
    }
    return null;
  }
}
