import { randomBytes } from "node:crypto";
import { closeSync, existsSync, fsyncSync, openSync, readFileSync, renameSync, unlinkSync, writeSync } from "node:fs";
import { join } from "node:path";
import { ensureDurableDir, fsyncDir, NODE_IO } from "../spine/durable_fs.js";
import { deriveDecompositionResultEventV1, isDecompositionResultEventV1, verifyDecompositionResultEventV1, type DecompositionResultEventCodeV1, type DecompositionResultEventV1, type DecompositionResultInputV1 } from "../spine/decomposition_result_events_v1.js";

export interface EnterpriseDecompositionJourneyRequestV1 extends DecompositionResultInputV1{readonly schema_version:1;readonly data_directory:string;readonly custody_evidence:"PRESENT"|"MISSING";readonly isolation_evidence:"PRESENT"|"MISSING";readonly public_seam_authorized:boolean;readonly implementation_authorized:false}
export type EnterpriseDecompositionJourneyReceiptV1=DecompositionResultEventV1&{readonly track:"enterprise"};
export type EnterpriseDecompositionJourneyCode="ENTERPRISE_DECOMPOSITION_JOURNEY_COMPLETE"|"ENTERPRISE_DECOMPOSITION_JOURNEY_RECOVERED"|"NO_DURABLE_JOURNEY"|"ENTERPRISE_CUSTODY_MISSING"|"PUBLIC_SEAM_BYPASS"|"DURABLE_JOURNEY_CONFLICT"|"MALFORMED_OR_UNKNOWN_FIELD"|"DECOMPOSITION_CANNOT_AUTHORIZE_IMPLEMENTATION"|DecompositionResultEventCodeV1;
export interface EnterpriseDecompositionJourneyResultV1{readonly advanced:boolean;readonly code:EnterpriseDecompositionJourneyCode;readonly receipt:EnterpriseDecompositionJourneyReceiptV1|null;readonly stage_invocations:Readonly<{reconstruction:number;activation:number}>}

const EVENT_FILE="enterprise-decomposition-result-event-v1.json";
const object=(value:unknown):value is Record<string,unknown>=>value!==null&&typeof value==="object"&&!Array.isArray(value);
const exact=(value:Record<string,unknown>,keys:readonly string[])=>{const actual=Object.keys(value).sort(),expected=[...keys].sort();return actual.length===expected.length&&actual.every((key,index)=>key===expected[index]);};
const validDirectory=(value:unknown):value is string=>typeof value==="string"&&value.length>0&&value.length<=4096&&!value.includes("\0");
const result=(code:EnterpriseDecompositionJourneyCode,receipt:EnterpriseDecompositionJourneyReceiptV1|null,reconstruction=0,activation=0):EnterpriseDecompositionJourneyResultV1=>Object.freeze({advanced:code==="ENTERPRISE_DECOMPOSITION_JOURNEY_COMPLETE"||code==="ENTERPRISE_DECOMPOSITION_JOURNEY_RECOVERED",code,receipt,stage_invocations:Object.freeze({reconstruction,activation})});
const pathFor=(directory:string)=>join(directory,EVENT_FILE);
function validateRequest(value:unknown):EnterpriseDecompositionJourneyRequestV1|EnterpriseDecompositionJourneyCode{let snapshot:unknown;try{snapshot=structuredClone(value);}catch{return "MALFORMED_OR_UNKNOWN_FIELD";}if(!object(snapshot)||!exact(snapshot,["activation","approval_history","approval_history_id","custody_evidence","data_directory","implementation_authorized","isolation_evidence","public_seam_authorized","review_history","review_history_id","schema_version"])||snapshot.schema_version!==1||!validDirectory(snapshot.data_directory)||!["PRESENT","MISSING"].includes(String(snapshot.custody_evidence))||!["PRESENT","MISSING"].includes(String(snapshot.isolation_evidence))||typeof snapshot.public_seam_authorized!=="boolean"||typeof snapshot.implementation_authorized!=="boolean")return "MALFORMED_OR_UNKNOWN_FIELD";if(!snapshot.public_seam_authorized)return "PUBLIC_SEAM_BYPASS";if(snapshot.custody_evidence==="MISSING"||snapshot.isolation_evidence==="MISSING")return "ENTERPRISE_CUSTODY_MISSING";if(snapshot.implementation_authorized||(object(snapshot.activation)&&snapshot.activation.implementation_authorized===true))return "DECOMPOSITION_CANNOT_AUTHORIZE_IMPLEMENTATION";if(!object(snapshot.activation)||!object(snapshot.activation.authority)||snapshot.activation.authority.kind!=="enterprise")return "TRACK_AUTHORITY_SUBSTITUTION";return snapshot as unknown as EnterpriseDecompositionJourneyRequestV1;}
type StoredEvent={readonly kind:"absent"}|{readonly kind:"invalid"}|{readonly kind:"value";readonly value:unknown};
function readEvent(directory:string):StoredEvent{const path=pathFor(directory);if(!existsSync(path))return {kind:"absent"};try{return {kind:"value",value:JSON.parse(readFileSync(path,"utf8")) as unknown};}catch{return {kind:"invalid"};}}
function writeEvent(directory:string,event:DecompositionResultEventV1):void{ensureDurableDir(NODE_IO,directory);const target=pathFor(directory),temporary=`${target}.${randomBytes(12).toString("hex")}.tmp`,bytes=Buffer.from(`${JSON.stringify(event)}\n`,"utf8");let fd:number|undefined;try{fd=openSync(temporary,"wx",0o600);for(let offset=0;offset<bytes.length;){const written=writeSync(fd,bytes,offset,bytes.length-offset);if(written<=0)throw new Error("durable event write made no progress");offset+=written;}fsyncSync(fd);closeSync(fd);fd=undefined;renameSync(temporary,target);fsyncDir(NODE_IO,directory);}finally{if(fd!==undefined)closeSync(fd);if(existsSync(temporary))unlinkSync(temporary);}}

/** Reconstruct committed decomposition authority, then persist one non-authoritative organization result event. */
export function runEnterpriseDecompositionJourney(value:EnterpriseDecompositionJourneyRequestV1):EnterpriseDecompositionJourneyResultV1{const checked=validateRequest(value);if(typeof checked==="string")return result(checked,null);const derived=deriveDecompositionResultEventV1(checked);if(!derived.ok)return result(derived.code,null,1,0);if(derived.event.track!=="enterprise")return result("TRACK_AUTHORITY_SUBSTITUTION",null,1,1);const durable=readEvent(checked.data_directory);if(durable.kind==="invalid")return result("DURABLE_JOURNEY_CONFLICT",null,1,1);if(durable.kind==="value"){const stored=durable.value;if(!isDecompositionResultEventV1(stored))return result("DURABLE_JOURNEY_CONFLICT",null,1,1);if(stored.event_digest!==derived.event.event_digest)return result("DURABLE_JOURNEY_CONFLICT",stored.track==="enterprise"?stored as EnterpriseDecompositionJourneyReceiptV1:null,1,1);}if(durable.kind==="absent")writeEvent(checked.data_directory,derived.event);return result("ENTERPRISE_DECOMPOSITION_JOURNEY_COMPLETE",derived.event as EnterpriseDecompositionJourneyReceiptV1,1,1);}

/** Recover evidence only after independently replaying the current committed histories. */
export function recoverEnterpriseDecompositionJourney(value:EnterpriseDecompositionJourneyRequestV1):EnterpriseDecompositionJourneyResultV1{const checked=validateRequest(value);if(typeof checked==="string")return result(checked,null);const durable=readEvent(checked.data_directory);if(durable.kind==="absent")return result("NO_DURABLE_JOURNEY",null);if(durable.kind==="invalid")return result("LEGACY_AUTHORITY_GAP",null);const verified=verifyDecompositionResultEventV1(checked,durable.value);if(!verified.ok)return result(verified.code,null,1,0);if(verified.event.track!=="enterprise")return result("TRACK_AUTHORITY_SUBSTITUTION",null,1,1);return result("ENTERPRISE_DECOMPOSITION_JOURNEY_RECOVERED",verified.event as EnterpriseDecompositionJourneyReceiptV1,1,1);}
